// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/account"
	"github.com/megalodev/setetes/internal/ent/bloodtype"
	"github.com/megalodev/setetes/internal/ent/password"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v int64) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountCreate) SetUpdatedAt(v int64) *AccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AccountCreate) SetDeletedAt(v int64) *AccountCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNationalIDHash sets the "national_id_hash" field.
func (_c *AccountCreate) SetNationalIDHash(v string) *AccountCreate {
	_c.mutation.SetNationalIDHash(v)
	return _c
}

// SetNationalIDMasked sets the "national_id_masked" field.
func (_c *AccountCreate) SetNationalIDMasked(v string) *AccountCreate {
	_c.mutation.SetNationalIDMasked(v)
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *AccountCreate) SetFullName(v string) *AccountCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetGender sets the "gender" field.
func (_c *AccountCreate) SetGender(v account.Gender) *AccountCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AccountCreate) SetEmail(v string) *AccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCountryIsoCode sets the "country_iso_code" field.
func (_c *AccountCreate) SetCountryIsoCode(v string) *AccountCreate {
	_c.mutation.SetCountryIsoCode(v)
	return _c
}

// SetDialCode sets the "dial_code" field.
func (_c *AccountCreate) SetDialCode(v string) *AccountCreate {
	_c.mutation.SetDialCode(v)
	return _c
}

// SetPhoneNumber sets the "phone_number" field.
func (_c *AccountCreate) SetPhoneNumber(v string) *AccountCreate {
	_c.mutation.SetPhoneNumber(v)
	return _c
}

// SetActivated sets the "activated" field.
func (_c *AccountCreate) SetActivated(v bool) *AccountCreate {
	_c.mutation.SetActivated(v)
	return _c
}

// SetNillableActivated sets the "activated" field if the given value is not nil.
func (_c *AccountCreate) SetNillableActivated(v *bool) *AccountCreate {
	if v != nil {
		_c.SetActivated(*v)
	}
	return _c
}

// SetLocked sets the "locked" field.
func (_c *AccountCreate) SetLocked(v bool) *AccountCreate {
	_c.mutation.SetLocked(v)
	return _c
}

// SetNillableLocked sets the "locked" field if the given value is not nil.
func (_c *AccountCreate) SetNillableLocked(v *bool) *AccountCreate {
	if v != nil {
		_c.SetLocked(*v)
	}
	return _c
}

// SetTempLockedAt sets the "temp_locked_at" field.
func (_c *AccountCreate) SetTempLockedAt(v int64) *AccountCreate {
	_c.mutation.SetTempLockedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetBloodTypeID sets the "blood_type" edge to the BloodType entity by ID.
func (_c *AccountCreate) SetBloodTypeID(id uuid.UUID) *AccountCreate {
	_c.mutation.SetBloodTypeID(id)
	return _c
}

// SetNillableBloodTypeID sets the "blood_type" edge to the BloodType entity by ID if the given value is not nil.
func (_c *AccountCreate) SetNillableBloodTypeID(id *uuid.UUID) *AccountCreate {
	if id != nil {
		_c = _c.SetBloodTypeID(*id)
	}
	return _c
}

// SetBloodType sets the "blood_type" edge to the BloodType entity.
func (_c *AccountCreate) SetBloodType(v *BloodType) *AccountCreate {
	return _c.SetBloodTypeID(v.ID)
}

// SetPasswordID sets the "password" edge to the Password entity by ID.
func (_c *AccountCreate) SetPasswordID(id uuid.UUID) *AccountCreate {
	_c.mutation.SetPasswordID(id)
	return _c
}

// SetNillablePasswordID sets the "password" edge to the Password entity by ID if the given value is not nil.
func (_c *AccountCreate) SetNillablePasswordID(id *uuid.UUID) *AccountCreate {
	if id != nil {
		_c = _c.SetPasswordID(*id)
	}
	return _c
}

// SetPassword sets the "password" edge to the Password entity.
func (_c *AccountCreate) SetPassword(v *Password) *AccountCreate {
	return _c.SetPasswordID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.Activated(); !ok {
		v := account.DefaultActivated
		_c.mutation.SetActivated(v)
	}
	if _, ok := _c.mutation.Locked(); !ok {
		v := account.DefaultLocked
		_c.mutation.SetLocked(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if v, ok := _c.mutation.CreatedAt(); ok {
		if err := account.CreatedAtValidator(v); err != nil {
			return &ValidationError{Name: "created_at", err: fmt.Errorf(`ent: validator failed for field "Account.created_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Account.updated_at"`)}
	}
	if v, ok := _c.mutation.UpdatedAt(); ok {
		if err := account.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "Account.updated_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Account.deleted_at"`)}
	}
	if v, ok := _c.mutation.DeletedAt(); ok {
		if err := account.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "Account.deleted_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NationalIDHash(); !ok {
		return &ValidationError{Name: "national_id_hash", err: errors.New(`ent: missing required field "Account.national_id_hash"`)}
	}
	if v, ok := _c.mutation.NationalIDHash(); ok {
		if err := account.NationalIDHashValidator(v); err != nil {
			return &ValidationError{Name: "national_id_hash", err: fmt.Errorf(`ent: validator failed for field "Account.national_id_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NationalIDMasked(); !ok {
		return &ValidationError{Name: "national_id_masked", err: errors.New(`ent: missing required field "Account.national_id_masked"`)}
	}
	if v, ok := _c.mutation.NationalIDMasked(); ok {
		if err := account.NationalIDMaskedValidator(v); err != nil {
			return &ValidationError{Name: "national_id_masked", err: fmt.Errorf(`ent: validator failed for field "Account.national_id_masked": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "Account.full_name"`)}
	}
	if v, ok := _c.mutation.FullName(); ok {
		if err := account.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Account.full_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Gender(); !ok {
		return &ValidationError{Name: "gender", err: errors.New(`ent: missing required field "Account.gender"`)}
	}
	if v, ok := _c.mutation.Gender(); ok {
		if err := account.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Account.gender": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Account.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := account.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Account.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CountryIsoCode(); !ok {
		return &ValidationError{Name: "country_iso_code", err: errors.New(`ent: missing required field "Account.country_iso_code"`)}
	}
	if v, ok := _c.mutation.CountryIsoCode(); ok {
		if err := account.CountryIsoCodeValidator(v); err != nil {
			return &ValidationError{Name: "country_iso_code", err: fmt.Errorf(`ent: validator failed for field "Account.country_iso_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DialCode(); !ok {
		return &ValidationError{Name: "dial_code", err: errors.New(`ent: missing required field "Account.dial_code"`)}
	}
	if v, ok := _c.mutation.DialCode(); ok {
		if err := account.DialCodeValidator(v); err != nil {
			return &ValidationError{Name: "dial_code", err: fmt.Errorf(`ent: validator failed for field "Account.dial_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PhoneNumber(); !ok {
		return &ValidationError{Name: "phone_number", err: errors.New(`ent: missing required field "Account.phone_number"`)}
	}
	if v, ok := _c.mutation.PhoneNumber(); ok {
		if err := account.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "Account.phone_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Activated(); !ok {
		return &ValidationError{Name: "activated", err: errors.New(`ent: missing required field "Account.activated"`)}
	}
	if _, ok := _c.mutation.Locked(); !ok {
		return &ValidationError{Name: "locked", err: errors.New(`ent: missing required field "Account.locked"`)}
	}
	if _, ok := _c.mutation.TempLockedAt(); !ok {
		return &ValidationError{Name: "temp_locked_at", err: errors.New(`ent: missing required field "Account.temp_locked_at"`)}
	}
	if v, ok := _c.mutation.TempLockedAt(); ok {
		if err := account.TempLockedAtValidator(v); err != nil {
			return &ValidationError{Name: "temp_locked_at", err: fmt.Errorf(`ent: validator failed for field "Account.temp_locked_at": %w`, err)}
		}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(account.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.NationalIDHash(); ok {
		_spec.SetField(account.FieldNationalIDHash, field.TypeString, value)
		_node.NationalIDHash = value
	}
	if value, ok := _c.mutation.NationalIDMasked(); ok {
		_spec.SetField(account.FieldNationalIDMasked, field.TypeString, value)
		_node.NationalIDMasked = value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(account.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(account.FieldGender, field.TypeEnum, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(account.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.CountryIsoCode(); ok {
		_spec.SetField(account.FieldCountryIsoCode, field.TypeString, value)
		_node.CountryIsoCode = value
	}
	if value, ok := _c.mutation.DialCode(); ok {
		_spec.SetField(account.FieldDialCode, field.TypeString, value)
		_node.DialCode = value
	}
	if value, ok := _c.mutation.PhoneNumber(); ok {
		_spec.SetField(account.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := _c.mutation.Activated(); ok {
		_spec.SetField(account.FieldActivated, field.TypeBool, value)
		_node.Activated = value
	}
	if value, ok := _c.mutation.Locked(); ok {
		_spec.SetField(account.FieldLocked, field.TypeBool, value)
		_node.Locked = value
	}
	if value, ok := _c.mutation.TempLockedAt(); ok {
		_spec.SetField(account.FieldTempLockedAt, field.TypeInt64, value)
		_node.TempLockedAt = &value
	}
	if nodes := _c.mutation.BloodTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.BloodTypeTable,
			Columns: []string{account.BloodTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bloodtype.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PasswordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.PasswordTable,
			Columns: []string{account.PasswordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(password.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
