// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/account"
	"github.com/megalodev/setetes/internal/ent/activation"
	"github.com/megalodev/setetes/internal/ent/predicate"
)

// ActivationUpdate is the builder for updating Activation entities.
type ActivationUpdate struct {
	config
	hooks    []Hook
	mutation *ActivationMutation
}

// Where appends a list predicates to the ActivationUpdate builder.
func (_u *ActivationUpdate) Where(ps ...predicate.Activation) *ActivationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivationUpdate) SetUpdatedAt(v int64) *ActivationUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ActivationUpdate) AddUpdatedAt(v int64) *ActivationUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ActivationUpdate) ClearUpdatedAt() *ActivationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ActivationUpdate) SetDeletedAt(v int64) *ActivationUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ActivationUpdate) SetNillableDeletedAt(v *int64) *ActivationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ActivationUpdate) AddDeletedAt(v int64) *ActivationUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ActivationUpdate) ClearDeletedAt() *ActivationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetToken sets the "token" field.
func (_u *ActivationUpdate) SetToken(v string) *ActivationUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ActivationUpdate) SetNillableToken(v *string) *ActivationUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetIsUsed sets the "is_used" field.
func (_u *ActivationUpdate) SetIsUsed(v bool) *ActivationUpdate {
	_u.mutation.SetIsUsed(v)
	return _u
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (_u *ActivationUpdate) SetNillableIsUsed(v *bool) *ActivationUpdate {
	if v != nil {
		_u.SetIsUsed(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *ActivationUpdate) SetExpiredAt(v int64) *ActivationUpdate {
	_u.mutation.ResetExpiredAt()
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *ActivationUpdate) SetNillableExpiredAt(v *int64) *ActivationUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// AddExpiredAt adds value to the "expired_at" field.
func (_u *ActivationUpdate) AddExpiredAt(v int64) *ActivationUpdate {
	_u.mutation.AddExpiredAt(v)
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *ActivationUpdate) SetAccountID(id uuid.UUID) *ActivationUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ActivationUpdate) SetAccount(v *Account) *ActivationUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ActivationMutation object of the builder.
func (_u *ActivationUpdate) Mutation() *ActivationMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ActivationUpdate) ClearAccount() *ActivationUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActivationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActivationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := activation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivationUpdate) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := activation.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "Activation.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := activation.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "Activation.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := activation.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Activation.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpiredAt(); ok {
		if err := activation.ExpiredAtValidator(v); err != nil {
			return &ValidationError{Name: "expired_at", err: fmt.Errorf(`ent: validator failed for field "Activation.expired_at": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Activation.account"`)
	}
	return nil
}

func (_u *ActivationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activation.Table, activation.Columns, sqlgraph.NewFieldSpec(activation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(activation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(activation.FieldUpdatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(activation.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(activation.FieldDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(activation.FieldDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(activation.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsUsed(); ok {
		_spec.SetField(activation.FieldIsUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(activation.FieldExpiredAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiredAt(); ok {
		_spec.AddField(activation.FieldExpiredAt, field.TypeInt64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   activation.AccountTable,
			Columns: []string{activation.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   activation.AccountTable,
			Columns: []string{activation.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActivationUpdateOne is the builder for updating a single Activation entity.
type ActivationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActivationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ActivationUpdateOne) SetUpdatedAt(v int64) *ActivationUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ActivationUpdateOne) AddUpdatedAt(v int64) *ActivationUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ActivationUpdateOne) ClearUpdatedAt() *ActivationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ActivationUpdateOne) SetDeletedAt(v int64) *ActivationUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ActivationUpdateOne) SetNillableDeletedAt(v *int64) *ActivationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ActivationUpdateOne) AddDeletedAt(v int64) *ActivationUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ActivationUpdateOne) ClearDeletedAt() *ActivationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetToken sets the "token" field.
func (_u *ActivationUpdateOne) SetToken(v string) *ActivationUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ActivationUpdateOne) SetNillableToken(v *string) *ActivationUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetIsUsed sets the "is_used" field.
func (_u *ActivationUpdateOne) SetIsUsed(v bool) *ActivationUpdateOne {
	_u.mutation.SetIsUsed(v)
	return _u
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (_u *ActivationUpdateOne) SetNillableIsUsed(v *bool) *ActivationUpdateOne {
	if v != nil {
		_u.SetIsUsed(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *ActivationUpdateOne) SetExpiredAt(v int64) *ActivationUpdateOne {
	_u.mutation.ResetExpiredAt()
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *ActivationUpdateOne) SetNillableExpiredAt(v *int64) *ActivationUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// AddExpiredAt adds value to the "expired_at" field.
func (_u *ActivationUpdateOne) AddExpiredAt(v int64) *ActivationUpdateOne {
	_u.mutation.AddExpiredAt(v)
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *ActivationUpdateOne) SetAccountID(id uuid.UUID) *ActivationUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ActivationUpdateOne) SetAccount(v *Account) *ActivationUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ActivationMutation object of the builder.
func (_u *ActivationUpdateOne) Mutation() *ActivationMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ActivationUpdateOne) ClearAccount() *ActivationUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the ActivationUpdate builder.
func (_u *ActivationUpdateOne) Where(ps ...predicate.Activation) *ActivationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActivationUpdateOne) Select(field string, fields ...string) *ActivationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Activation entity.
func (_u *ActivationUpdateOne) Save(ctx context.Context) (*Activation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActivationUpdateOne) SaveX(ctx context.Context) *Activation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActivationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActivationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActivationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := activation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActivationUpdateOne) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := activation.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "Activation.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := activation.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "Activation.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := activation.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Activation.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpiredAt(); ok {
		if err := activation.ExpiredAtValidator(v); err != nil {
			return &ValidationError{Name: "expired_at", err: fmt.Errorf(`ent: validator failed for field "Activation.expired_at": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Activation.account"`)
	}
	return nil
}

func (_u *ActivationUpdateOne) sqlSave(ctx context.Context) (_node *Activation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(activation.Table, activation.Columns, sqlgraph.NewFieldSpec(activation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Activation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, activation.FieldID)
		for _, f := range fields {
			if !activation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != activation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(activation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(activation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(activation.FieldUpdatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(activation.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(activation.FieldDeletedAt, field.TypeInt64, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(activation.FieldDeletedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(activation.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsUsed(); ok {
		_spec.SetField(activation.FieldIsUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(activation.FieldExpiredAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiredAt(); ok {
		_spec.AddField(activation.FieldExpiredAt, field.TypeInt64, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   activation.AccountTable,
			Columns: []string{activation.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   activation.AccountTable,
			Columns: []string{activation.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Activation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{activation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
