// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sembraniteam/setetes/internal/ent/account"
	"github.com/sembraniteam/setetes/internal/ent/bloodtype"
)

// BloodTypeCreate is the builder for creating a BloodType entity.
type BloodTypeCreate struct {
	config
	mutation *BloodTypeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *BloodTypeCreate) SetCreatedAt(v int64) *BloodTypeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BloodTypeCreate) SetUpdatedAt(v int64) *BloodTypeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BloodTypeCreate) SetNillableUpdatedAt(v *int64) *BloodTypeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BloodTypeCreate) SetDeletedAt(v int64) *BloodTypeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BloodTypeCreate) SetNillableDeletedAt(v *int64) *BloodTypeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetGroup sets the "group" field.
func (_c *BloodTypeCreate) SetGroup(v bloodtype.Group) *BloodTypeCreate {
	_c.mutation.SetGroup(v)
	return _c
}

// SetRhesus sets the "rhesus" field.
func (_c *BloodTypeCreate) SetRhesus(v bloodtype.Rhesus) *BloodTypeCreate {
	_c.mutation.SetRhesus(v)
	return _c
}

// SetNillableRhesus sets the "rhesus" field if the given value is not nil.
func (_c *BloodTypeCreate) SetNillableRhesus(v *bloodtype.Rhesus) *BloodTypeCreate {
	if v != nil {
		_c.SetRhesus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BloodTypeCreate) SetID(v uuid.UUID) *BloodTypeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *BloodTypeCreate) SetAccountID(id uuid.UUID) *BloodTypeCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *BloodTypeCreate) SetAccount(v *Account) *BloodTypeCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the BloodTypeMutation object of the builder.
func (_c *BloodTypeCreate) Mutation() *BloodTypeMutation {
	return _c.mutation
}

// Save creates the BloodType in the database.
func (_c *BloodTypeCreate) Save(ctx context.Context) (*BloodType, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BloodTypeCreate) SaveX(ctx context.Context) *BloodType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BloodTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BloodTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BloodTypeCreate) check() error {
	if v, ok := _c.mutation.CreatedAt(); ok {
		if err := bloodtype.CreatedAtValidator(v); err != nil {
			return &ValidationError{Name: "created_at", err: fmt.Errorf(`ent: validator failed for field "BloodType.created_at": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpdatedAt(); ok {
		if err := bloodtype.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "BloodType.updated_at": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeletedAt(); ok {
		if err := bloodtype.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "BloodType.deleted_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Group(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required field "BloodType.group"`)}
	}
	if v, ok := _c.mutation.Group(); ok {
		if err := bloodtype.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "BloodType.group": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Rhesus(); ok {
		if err := bloodtype.RhesusValidator(v); err != nil {
			return &ValidationError{Name: "rhesus", err: fmt.Errorf(`ent: validator failed for field "BloodType.rhesus": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "BloodType.account"`)}
	}
	return nil
}

func (_c *BloodTypeCreate) sqlSave(ctx context.Context) (*BloodType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BloodTypeCreate) createSpec() (*BloodType, *sqlgraph.CreateSpec) {
	var (
		_node = &BloodType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bloodtype.Table, sqlgraph.NewFieldSpec(bloodtype.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bloodtype.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(bloodtype.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(bloodtype.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Group(); ok {
		_spec.SetField(bloodtype.FieldGroup, field.TypeEnum, value)
		_node.Group = value
	}
	if value, ok := _c.mutation.Rhesus(); ok {
		_spec.SetField(bloodtype.FieldRhesus, field.TypeEnum, value)
		_node.Rhesus = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bloodtype.AccountTable,
			Columns: []string{bloodtype.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.account_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BloodTypeCreateBulk is the builder for creating many BloodType entities in bulk.
type BloodTypeCreateBulk struct {
	config
	err      error
	builders []*BloodTypeCreate
}

// Save creates the BloodType entities in the database.
func (_c *BloodTypeCreateBulk) Save(ctx context.Context) ([]*BloodType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BloodType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BloodTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BloodTypeCreateBulk) SaveX(ctx context.Context) []*BloodType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BloodTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BloodTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
