// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sembraniteam/setetes/internal/ent/account"
	"github.com/sembraniteam/setetes/internal/ent/bloodtype"
)

// BloodType is the model entity for the BloodType schema.
type BloodType struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at"`
	// Represents soft delete timestamp in milliseconds.
	DeletedAt int64 `json:"deleted_at"`
	// comment:The ABO blood group classification (A, B, AB, or O).
	Group bloodtype.Group `json:"group"`
	// The Rhesus (Rh) factor of the blood group, either POSITIVE or NEGATIVE.
	Rhesus bloodtype.Rhesus `json:"rhesus"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BloodTypeQuery when eager-loading is set.
	Edges        BloodTypeEdges `json:"edges"`
	account_id   *uuid.UUID
	selectValues sql.SelectValues
}

// BloodTypeEdges holds the relations/edges for other nodes in the graph.
type BloodTypeEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BloodTypeEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BloodType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bloodtype.FieldCreatedAt, bloodtype.FieldUpdatedAt, bloodtype.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case bloodtype.FieldGroup, bloodtype.FieldRhesus:
			values[i] = new(sql.NullString)
		case bloodtype.FieldID:
			values[i] = new(uuid.UUID)
		case bloodtype.ForeignKeys[0]: // account_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BloodType fields.
func (_m *BloodType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bloodtype.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bloodtype.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case bloodtype.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Int64
			}
		case bloodtype.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Int64
			}
		case bloodtype.FieldGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group", values[i])
			} else if value.Valid {
				_m.Group = bloodtype.Group(value.String)
			}
		case bloodtype.FieldRhesus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rhesus", values[i])
			} else if value.Valid {
				_m.Rhesus = bloodtype.Rhesus(value.String)
			}
		case bloodtype.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.account_id = new(uuid.UUID)
				*_m.account_id = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BloodType.
// This includes values selected through modifiers, order, etc.
func (_m *BloodType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the BloodType entity.
func (_m *BloodType) QueryAccount() *AccountQuery {
	return NewBloodTypeClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this BloodType.
// Note that you need to call BloodType.Unwrap() before calling this method if this BloodType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BloodType) Update() *BloodTypeUpdateOne {
	return NewBloodTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BloodType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BloodType) Unwrap() *BloodType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BloodType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BloodType) String() string {
	var builder strings.Builder
	builder.WriteString("BloodType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("group=")
	builder.WriteString(fmt.Sprintf("%v", _m.Group))
	builder.WriteString(", ")
	builder.WriteString("rhesus=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rhesus))
	builder.WriteByte(')')
	return builder.String()
}

// BloodTypes is a parsable slice of BloodType.
type BloodTypes []*BloodType
