// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/pmilocation"
	"github.com/megalodev/setetes/internal/ent/schema"
	"github.com/megalodev/setetes/internal/ent/subdistrict"
)

// PMILocationCreate is the builder for creating a PMILocation entity.
type PMILocationCreate struct {
	config
	mutation *PMILocationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PMILocationCreate) SetCreatedAt(v int64) *PMILocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PMILocationCreate) SetUpdatedAt(v int64) *PMILocationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PMILocationCreate) SetDeletedAt(v int64) *PMILocationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PMILocationCreate) SetName(v string) *PMILocationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBedCapacities sets the "bed_capacities" field.
func (_c *PMILocationCreate) SetBedCapacities(v int16) *PMILocationCreate {
	_c.mutation.SetBedCapacities(v)
	return _c
}

// SetNillableBedCapacities sets the "bed_capacities" field if the given value is not nil.
func (_c *PMILocationCreate) SetNillableBedCapacities(v *int16) *PMILocationCreate {
	if v != nil {
		_c.SetBedCapacities(*v)
	}
	return _c
}

// SetLatLng sets the "lat_lng" field.
func (_c *PMILocationCreate) SetLatLng(v *schema.GeoPoint) *PMILocationCreate {
	_c.mutation.SetLatLng(v)
	return _c
}

// SetStreet sets the "street" field.
func (_c *PMILocationCreate) SetStreet(v string) *PMILocationCreate {
	_c.mutation.SetStreet(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *PMILocationCreate) SetEmail(v string) *PMILocationCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetDialCode sets the "dial_code" field.
func (_c *PMILocationCreate) SetDialCode(v string) *PMILocationCreate {
	_c.mutation.SetDialCode(v)
	return _c
}

// SetPhoneNumber sets the "phone_number" field.
func (_c *PMILocationCreate) SetPhoneNumber(v string) *PMILocationCreate {
	_c.mutation.SetPhoneNumber(v)
	return _c
}

// SetOpensAt sets the "opens_at" field.
func (_c *PMILocationCreate) SetOpensAt(v time.Time) *PMILocationCreate {
	_c.mutation.SetOpensAt(v)
	return _c
}

// SetClosesAt sets the "closes_at" field.
func (_c *PMILocationCreate) SetClosesAt(v time.Time) *PMILocationCreate {
	_c.mutation.SetClosesAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PMILocationCreate) SetID(v uuid.UUID) *PMILocationCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSubdistrictIDs adds the "subdistrict" edge to the Subdistrict entity by IDs.
func (_c *PMILocationCreate) AddSubdistrictIDs(ids ...uuid.UUID) *PMILocationCreate {
	_c.mutation.AddSubdistrictIDs(ids...)
	return _c
}

// AddSubdistrict adds the "subdistrict" edges to the Subdistrict entity.
func (_c *PMILocationCreate) AddSubdistrict(v ...*Subdistrict) *PMILocationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubdistrictIDs(ids...)
}

// Mutation returns the PMILocationMutation object of the builder.
func (_c *PMILocationCreate) Mutation() *PMILocationMutation {
	return _c.mutation
}

// Save creates the PMILocation in the database.
func (_c *PMILocationCreate) Save(ctx context.Context) (*PMILocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PMILocationCreate) SaveX(ctx context.Context) *PMILocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PMILocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PMILocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PMILocationCreate) defaults() {
	if _, ok := _c.mutation.BedCapacities(); !ok {
		v := pmilocation.DefaultBedCapacities
		_c.mutation.SetBedCapacities(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PMILocationCreate) check() error {
	if v, ok := _c.mutation.CreatedAt(); ok {
		if err := pmilocation.CreatedAtValidator(v); err != nil {
			return &ValidationError{Name: "created_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.created_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PMILocation.updated_at"`)}
	}
	if v, ok := _c.mutation.UpdatedAt(); ok {
		if err := pmilocation.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.updated_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "PMILocation.deleted_at"`)}
	}
	if v, ok := _c.mutation.DeletedAt(); ok {
		if err := pmilocation.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.deleted_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PMILocation.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := pmilocation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PMILocation.name": %w`, err)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.BedCapacities(); !ok {
			return &ValidationError{Name: "bed_capacities", err: errors.New(`ent: missing required field "PMILocation.bed_capacities"`)}
		}
	}
	if v, ok := _c.mutation.BedCapacities(); ok {
		if err := pmilocation.BedCapacitiesValidator(v); err != nil {
			return &ValidationError{Name: "bed_capacities", err: fmt.Errorf(`ent: validator failed for field "PMILocation.bed_capacities": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LatLng(); !ok {
		return &ValidationError{Name: "lat_lng", err: errors.New(`ent: missing required field "PMILocation.lat_lng"`)}
	}
	if _, ok := _c.mutation.Street(); !ok {
		return &ValidationError{Name: "street", err: errors.New(`ent: missing required field "PMILocation.street"`)}
	}
	if v, ok := _c.mutation.Street(); ok {
		if err := pmilocation.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "PMILocation.street": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "PMILocation.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := pmilocation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PMILocation.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DialCode(); !ok {
		return &ValidationError{Name: "dial_code", err: errors.New(`ent: missing required field "PMILocation.dial_code"`)}
	}
	if _, ok := _c.mutation.PhoneNumber(); !ok {
		return &ValidationError{Name: "phone_number", err: errors.New(`ent: missing required field "PMILocation.phone_number"`)}
	}
	if v, ok := _c.mutation.PhoneNumber(); ok {
		if err := pmilocation.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "PMILocation.phone_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpensAt(); !ok {
		return &ValidationError{Name: "opens_at", err: errors.New(`ent: missing required field "PMILocation.opens_at"`)}
	}
	if _, ok := _c.mutation.ClosesAt(); !ok {
		return &ValidationError{Name: "closes_at", err: errors.New(`ent: missing required field "PMILocation.closes_at"`)}
	}
	return nil
}

func (_c *PMILocationCreate) sqlSave(ctx context.Context) (*PMILocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PMILocationCreate) createSpec() (*PMILocation, *sqlgraph.CreateSpec) {
	var (
		_node = &PMILocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pmilocation.Table, sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pmilocation.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pmilocation.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(pmilocation.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(pmilocation.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BedCapacities(); ok {
		_spec.SetField(pmilocation.FieldBedCapacities, field.TypeInt16, value)
		_node.BedCapacities = value
	}
	if value, ok := _c.mutation.LatLng(); ok {
		_spec.SetField(pmilocation.FieldLatLng, field.TypeOther, value)
		_node.LatLng = value
	}
	if value, ok := _c.mutation.Street(); ok {
		_spec.SetField(pmilocation.FieldStreet, field.TypeString, value)
		_node.Street = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(pmilocation.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.DialCode(); ok {
		_spec.SetField(pmilocation.FieldDialCode, field.TypeString, value)
		_node.DialCode = value
	}
	if value, ok := _c.mutation.PhoneNumber(); ok {
		_spec.SetField(pmilocation.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := _c.mutation.OpensAt(); ok {
		_spec.SetField(pmilocation.FieldOpensAt, field.TypeTime, value)
		_node.OpensAt = value
	}
	if value, ok := _c.mutation.ClosesAt(); ok {
		_spec.SetField(pmilocation.FieldClosesAt, field.TypeTime, value)
		_node.ClosesAt = value
	}
	if nodes := _c.mutation.SubdistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pmilocation.SubdistrictTable,
			Columns: []string{pmilocation.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PMILocationCreateBulk is the builder for creating many PMILocation entities in bulk.
type PMILocationCreateBulk struct {
	config
	err      error
	builders []*PMILocationCreate
}

// Save creates the PMILocation entities in the database.
func (_c *PMILocationCreateBulk) Save(ctx context.Context) ([]*PMILocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PMILocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PMILocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PMILocationCreateBulk) SaveX(ctx context.Context) []*PMILocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PMILocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PMILocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
