// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/pmilocation"
	"github.com/megalodev/setetes/internal/ent/predicate"
	"github.com/megalodev/setetes/internal/ent/subdistrict"
)

// PMILocationUpdate is the builder for updating PMILocation entities.
type PMILocationUpdate struct {
	config
	hooks    []Hook
	mutation *PMILocationMutation
}

// Where appends a list predicates to the PMILocationUpdate builder.
func (_u *PMILocationUpdate) Where(ps ...predicate.PMILocation) *PMILocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PMILocationUpdate) SetUpdatedAt(v int64) *PMILocationUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *PMILocationUpdate) AddUpdatedAt(v int64) *PMILocationUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PMILocationUpdate) SetDeletedAt(v int64) *PMILocationUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableDeletedAt(v *int64) *PMILocationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *PMILocationUpdate) AddDeletedAt(v int64) *PMILocationUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PMILocationUpdate) SetName(v string) *PMILocationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableName(v *string) *PMILocationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBedCapacities sets the "bed_capacities" field.
func (_u *PMILocationUpdate) SetBedCapacities(v int) *PMILocationUpdate {
	_u.mutation.ResetBedCapacities()
	_u.mutation.SetBedCapacities(v)
	return _u
}

// SetNillableBedCapacities sets the "bed_capacities" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableBedCapacities(v *int) *PMILocationUpdate {
	if v != nil {
		_u.SetBedCapacities(*v)
	}
	return _u
}

// AddBedCapacities adds value to the "bed_capacities" field.
func (_u *PMILocationUpdate) AddBedCapacities(v int) *PMILocationUpdate {
	_u.mutation.AddBedCapacities(v)
	return _u
}

// SetLat sets the "lat" field.
func (_u *PMILocationUpdate) SetLat(v float64) *PMILocationUpdate {
	_u.mutation.ResetLat()
	_u.mutation.SetLat(v)
	return _u
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableLat(v *float64) *PMILocationUpdate {
	if v != nil {
		_u.SetLat(*v)
	}
	return _u
}

// AddLat adds value to the "lat" field.
func (_u *PMILocationUpdate) AddLat(v float64) *PMILocationUpdate {
	_u.mutation.AddLat(v)
	return _u
}

// SetLng sets the "lng" field.
func (_u *PMILocationUpdate) SetLng(v float64) *PMILocationUpdate {
	_u.mutation.ResetLng()
	_u.mutation.SetLng(v)
	return _u
}

// SetNillableLng sets the "lng" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableLng(v *float64) *PMILocationUpdate {
	if v != nil {
		_u.SetLng(*v)
	}
	return _u
}

// AddLng adds value to the "lng" field.
func (_u *PMILocationUpdate) AddLng(v float64) *PMILocationUpdate {
	_u.mutation.AddLng(v)
	return _u
}

// SetStreet sets the "street" field.
func (_u *PMILocationUpdate) SetStreet(v string) *PMILocationUpdate {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableStreet(v *string) *PMILocationUpdate {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *PMILocationUpdate) SetEmail(v string) *PMILocationUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableEmail(v *string) *PMILocationUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *PMILocationUpdate) SetPhoneNumber(v string) *PMILocationUpdate {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillablePhoneNumber(v *string) *PMILocationUpdate {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// SetOpensAt sets the "opens_at" field.
func (_u *PMILocationUpdate) SetOpensAt(v int) *PMILocationUpdate {
	_u.mutation.ResetOpensAt()
	_u.mutation.SetOpensAt(v)
	return _u
}

// SetNillableOpensAt sets the "opens_at" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableOpensAt(v *int) *PMILocationUpdate {
	if v != nil {
		_u.SetOpensAt(*v)
	}
	return _u
}

// AddOpensAt adds value to the "opens_at" field.
func (_u *PMILocationUpdate) AddOpensAt(v int) *PMILocationUpdate {
	_u.mutation.AddOpensAt(v)
	return _u
}

// SetClosesAt sets the "closes_at" field.
func (_u *PMILocationUpdate) SetClosesAt(v int) *PMILocationUpdate {
	_u.mutation.ResetClosesAt()
	_u.mutation.SetClosesAt(v)
	return _u
}

// SetNillableClosesAt sets the "closes_at" field if the given value is not nil.
func (_u *PMILocationUpdate) SetNillableClosesAt(v *int) *PMILocationUpdate {
	if v != nil {
		_u.SetClosesAt(*v)
	}
	return _u
}

// AddClosesAt adds value to the "closes_at" field.
func (_u *PMILocationUpdate) AddClosesAt(v int) *PMILocationUpdate {
	_u.mutation.AddClosesAt(v)
	return _u
}

// AddSubdistrictIDs adds the "subdistrict" edge to the Subdistrict entity by IDs.
func (_u *PMILocationUpdate) AddSubdistrictIDs(ids ...uuid.UUID) *PMILocationUpdate {
	_u.mutation.AddSubdistrictIDs(ids...)
	return _u
}

// AddSubdistrict adds the "subdistrict" edges to the Subdistrict entity.
func (_u *PMILocationUpdate) AddSubdistrict(v ...*Subdistrict) *PMILocationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubdistrictIDs(ids...)
}

// Mutation returns the PMILocationMutation object of the builder.
func (_u *PMILocationUpdate) Mutation() *PMILocationMutation {
	return _u.mutation
}

// ClearSubdistrict clears all "subdistrict" edges to the Subdistrict entity.
func (_u *PMILocationUpdate) ClearSubdistrict() *PMILocationUpdate {
	_u.mutation.ClearSubdistrict()
	return _u
}

// RemoveSubdistrictIDs removes the "subdistrict" edge to Subdistrict entities by IDs.
func (_u *PMILocationUpdate) RemoveSubdistrictIDs(ids ...uuid.UUID) *PMILocationUpdate {
	_u.mutation.RemoveSubdistrictIDs(ids...)
	return _u
}

// RemoveSubdistrict removes "subdistrict" edges to Subdistrict entities.
func (_u *PMILocationUpdate) RemoveSubdistrict(v ...*Subdistrict) *PMILocationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubdistrictIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PMILocationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PMILocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PMILocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PMILocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PMILocationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pmilocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PMILocationUpdate) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := pmilocation.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := pmilocation.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := pmilocation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PMILocation.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BedCapacities(); ok {
		if err := pmilocation.BedCapacitiesValidator(v); err != nil {
			return &ValidationError{Name: "bed_capacities", err: fmt.Errorf(`ent: validator failed for field "PMILocation.bed_capacities": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Street(); ok {
		if err := pmilocation.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "PMILocation.street": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := pmilocation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PMILocation.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PhoneNumber(); ok {
		if err := pmilocation.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "PMILocation.phone_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OpensAt(); ok {
		if err := pmilocation.OpensAtValidator(v); err != nil {
			return &ValidationError{Name: "opens_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.opens_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClosesAt(); ok {
		if err := pmilocation.ClosesAtValidator(v); err != nil {
			return &ValidationError{Name: "closes_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.closes_at": %w`, err)}
		}
	}
	return nil
}

func (_u *PMILocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pmilocation.Table, pmilocation.Columns, sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pmilocation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(pmilocation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pmilocation.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(pmilocation.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pmilocation.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BedCapacities(); ok {
		_spec.SetField(pmilocation.FieldBedCapacities, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBedCapacities(); ok {
		_spec.AddField(pmilocation.FieldBedCapacities, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Lat(); ok {
		_spec.SetField(pmilocation.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLat(); ok {
		_spec.AddField(pmilocation.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Lng(); ok {
		_spec.SetField(pmilocation.FieldLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLng(); ok {
		_spec.AddField(pmilocation.FieldLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(pmilocation.FieldStreet, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(pmilocation.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(pmilocation.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpensAt(); ok {
		_spec.SetField(pmilocation.FieldOpensAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpensAt(); ok {
		_spec.AddField(pmilocation.FieldOpensAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClosesAt(); ok {
		_spec.SetField(pmilocation.FieldClosesAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClosesAt(); ok {
		_spec.AddField(pmilocation.FieldClosesAt, field.TypeInt, value)
	}
	if _u.mutation.SubdistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pmilocation.SubdistrictTable,
			Columns: []string{pmilocation.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubdistrictIDs(); len(nodes) > 0 && !_u.mutation.SubdistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pmilocation.SubdistrictTable,
			Columns: []string{pmilocation.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubdistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pmilocation.SubdistrictTable,
			Columns: []string{pmilocation.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pmilocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PMILocationUpdateOne is the builder for updating a single PMILocation entity.
type PMILocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PMILocationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PMILocationUpdateOne) SetUpdatedAt(v int64) *PMILocationUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *PMILocationUpdateOne) AddUpdatedAt(v int64) *PMILocationUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PMILocationUpdateOne) SetDeletedAt(v int64) *PMILocationUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableDeletedAt(v *int64) *PMILocationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *PMILocationUpdateOne) AddDeletedAt(v int64) *PMILocationUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PMILocationUpdateOne) SetName(v string) *PMILocationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableName(v *string) *PMILocationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBedCapacities sets the "bed_capacities" field.
func (_u *PMILocationUpdateOne) SetBedCapacities(v int) *PMILocationUpdateOne {
	_u.mutation.ResetBedCapacities()
	_u.mutation.SetBedCapacities(v)
	return _u
}

// SetNillableBedCapacities sets the "bed_capacities" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableBedCapacities(v *int) *PMILocationUpdateOne {
	if v != nil {
		_u.SetBedCapacities(*v)
	}
	return _u
}

// AddBedCapacities adds value to the "bed_capacities" field.
func (_u *PMILocationUpdateOne) AddBedCapacities(v int) *PMILocationUpdateOne {
	_u.mutation.AddBedCapacities(v)
	return _u
}

// SetLat sets the "lat" field.
func (_u *PMILocationUpdateOne) SetLat(v float64) *PMILocationUpdateOne {
	_u.mutation.ResetLat()
	_u.mutation.SetLat(v)
	return _u
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableLat(v *float64) *PMILocationUpdateOne {
	if v != nil {
		_u.SetLat(*v)
	}
	return _u
}

// AddLat adds value to the "lat" field.
func (_u *PMILocationUpdateOne) AddLat(v float64) *PMILocationUpdateOne {
	_u.mutation.AddLat(v)
	return _u
}

// SetLng sets the "lng" field.
func (_u *PMILocationUpdateOne) SetLng(v float64) *PMILocationUpdateOne {
	_u.mutation.ResetLng()
	_u.mutation.SetLng(v)
	return _u
}

// SetNillableLng sets the "lng" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableLng(v *float64) *PMILocationUpdateOne {
	if v != nil {
		_u.SetLng(*v)
	}
	return _u
}

// AddLng adds value to the "lng" field.
func (_u *PMILocationUpdateOne) AddLng(v float64) *PMILocationUpdateOne {
	_u.mutation.AddLng(v)
	return _u
}

// SetStreet sets the "street" field.
func (_u *PMILocationUpdateOne) SetStreet(v string) *PMILocationUpdateOne {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableStreet(v *string) *PMILocationUpdateOne {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *PMILocationUpdateOne) SetEmail(v string) *PMILocationUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableEmail(v *string) *PMILocationUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *PMILocationUpdateOne) SetPhoneNumber(v string) *PMILocationUpdateOne {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillablePhoneNumber(v *string) *PMILocationUpdateOne {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// SetOpensAt sets the "opens_at" field.
func (_u *PMILocationUpdateOne) SetOpensAt(v int) *PMILocationUpdateOne {
	_u.mutation.ResetOpensAt()
	_u.mutation.SetOpensAt(v)
	return _u
}

// SetNillableOpensAt sets the "opens_at" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableOpensAt(v *int) *PMILocationUpdateOne {
	if v != nil {
		_u.SetOpensAt(*v)
	}
	return _u
}

// AddOpensAt adds value to the "opens_at" field.
func (_u *PMILocationUpdateOne) AddOpensAt(v int) *PMILocationUpdateOne {
	_u.mutation.AddOpensAt(v)
	return _u
}

// SetClosesAt sets the "closes_at" field.
func (_u *PMILocationUpdateOne) SetClosesAt(v int) *PMILocationUpdateOne {
	_u.mutation.ResetClosesAt()
	_u.mutation.SetClosesAt(v)
	return _u
}

// SetNillableClosesAt sets the "closes_at" field if the given value is not nil.
func (_u *PMILocationUpdateOne) SetNillableClosesAt(v *int) *PMILocationUpdateOne {
	if v != nil {
		_u.SetClosesAt(*v)
	}
	return _u
}

// AddClosesAt adds value to the "closes_at" field.
func (_u *PMILocationUpdateOne) AddClosesAt(v int) *PMILocationUpdateOne {
	_u.mutation.AddClosesAt(v)
	return _u
}

// AddSubdistrictIDs adds the "subdistrict" edge to the Subdistrict entity by IDs.
func (_u *PMILocationUpdateOne) AddSubdistrictIDs(ids ...uuid.UUID) *PMILocationUpdateOne {
	_u.mutation.AddSubdistrictIDs(ids...)
	return _u
}

// AddSubdistrict adds the "subdistrict" edges to the Subdistrict entity.
func (_u *PMILocationUpdateOne) AddSubdistrict(v ...*Subdistrict) *PMILocationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubdistrictIDs(ids...)
}

// Mutation returns the PMILocationMutation object of the builder.
func (_u *PMILocationUpdateOne) Mutation() *PMILocationMutation {
	return _u.mutation
}

// ClearSubdistrict clears all "subdistrict" edges to the Subdistrict entity.
func (_u *PMILocationUpdateOne) ClearSubdistrict() *PMILocationUpdateOne {
	_u.mutation.ClearSubdistrict()
	return _u
}

// RemoveSubdistrictIDs removes the "subdistrict" edge to Subdistrict entities by IDs.
func (_u *PMILocationUpdateOne) RemoveSubdistrictIDs(ids ...uuid.UUID) *PMILocationUpdateOne {
	_u.mutation.RemoveSubdistrictIDs(ids...)
	return _u
}

// RemoveSubdistrict removes "subdistrict" edges to Subdistrict entities.
func (_u *PMILocationUpdateOne) RemoveSubdistrict(v ...*Subdistrict) *PMILocationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubdistrictIDs(ids...)
}

// Where appends a list predicates to the PMILocationUpdate builder.
func (_u *PMILocationUpdateOne) Where(ps ...predicate.PMILocation) *PMILocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PMILocationUpdateOne) Select(field string, fields ...string) *PMILocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PMILocation entity.
func (_u *PMILocationUpdateOne) Save(ctx context.Context) (*PMILocation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PMILocationUpdateOne) SaveX(ctx context.Context) *PMILocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PMILocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PMILocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PMILocationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pmilocation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PMILocationUpdateOne) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := pmilocation.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := pmilocation.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := pmilocation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PMILocation.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BedCapacities(); ok {
		if err := pmilocation.BedCapacitiesValidator(v); err != nil {
			return &ValidationError{Name: "bed_capacities", err: fmt.Errorf(`ent: validator failed for field "PMILocation.bed_capacities": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Street(); ok {
		if err := pmilocation.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "PMILocation.street": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := pmilocation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PMILocation.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PhoneNumber(); ok {
		if err := pmilocation.PhoneNumberValidator(v); err != nil {
			return &ValidationError{Name: "phone_number", err: fmt.Errorf(`ent: validator failed for field "PMILocation.phone_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OpensAt(); ok {
		if err := pmilocation.OpensAtValidator(v); err != nil {
			return &ValidationError{Name: "opens_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.opens_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClosesAt(); ok {
		if err := pmilocation.ClosesAtValidator(v); err != nil {
			return &ValidationError{Name: "closes_at", err: fmt.Errorf(`ent: validator failed for field "PMILocation.closes_at": %w`, err)}
		}
	}
	return nil
}

func (_u *PMILocationUpdateOne) sqlSave(ctx context.Context) (_node *PMILocation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pmilocation.Table, pmilocation.Columns, sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PMILocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pmilocation.FieldID)
		for _, f := range fields {
			if !pmilocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pmilocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pmilocation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(pmilocation.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pmilocation.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(pmilocation.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pmilocation.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BedCapacities(); ok {
		_spec.SetField(pmilocation.FieldBedCapacities, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBedCapacities(); ok {
		_spec.AddField(pmilocation.FieldBedCapacities, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Lat(); ok {
		_spec.SetField(pmilocation.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLat(); ok {
		_spec.AddField(pmilocation.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Lng(); ok {
		_spec.SetField(pmilocation.FieldLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLng(); ok {
		_spec.AddField(pmilocation.FieldLng, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(pmilocation.FieldStreet, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(pmilocation.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(pmilocation.FieldPhoneNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpensAt(); ok {
		_spec.SetField(pmilocation.FieldOpensAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpensAt(); ok {
		_spec.AddField(pmilocation.FieldOpensAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClosesAt(); ok {
		_spec.SetField(pmilocation.FieldClosesAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClosesAt(); ok {
		_spec.AddField(pmilocation.FieldClosesAt, field.TypeInt, value)
	}
	if _u.mutation.SubdistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pmilocation.SubdistrictTable,
			Columns: []string{pmilocation.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubdistrictIDs(); len(nodes) > 0 && !_u.mutation.SubdistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pmilocation.SubdistrictTable,
			Columns: []string{pmilocation.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubdistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pmilocation.SubdistrictTable,
			Columns: []string{pmilocation.SubdistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PMILocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pmilocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
