// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/pmilocation"
	"github.com/megalodev/setetes/internal/ent/schema"
	"github.com/megalodev/setetes/internal/ent/subdistrict"
)

// PMILocation is the model entity for the PMILocation schema.
type PMILocation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at"`
	// Represents soft delete timestamp in milliseconds.
	DeletedAt int64 `json:"deleted_at"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// BedCapacities holds the value of the "bed_capacities" field.
	BedCapacities int16 `json:"bed_capacities"`
	// LatLng holds the value of the "lat_lng" field.
	LatLng *schema.GeoPoint `json:"lat_lng"`
	// Street holds the value of the "street" field.
	Street string `json:"street"`
	// Email holds the value of the "email" field.
	Email string `json:"email"`
	// International dialing code of the user's country (e.g., 62 for Indonesia, 1 for United States),  without '+'. Used for constructing complete phone numbers.
	DialCode string `json:"dial_code"`
	// PhoneNumber holds the value of the "phone_number" field.
	PhoneNumber string `json:"phone_number"`
	// OpensAt holds the value of the "opens_at" field.
	OpensAt time.Time `json:"opens_at"`
	// ClosesAt holds the value of the "closes_at" field.
	ClosesAt time.Time `json:"closes_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PMILocationQuery when eager-loading is set.
	Edges          PMILocationEdges `json:"edges"`
	subdistrict_id *uuid.UUID
	selectValues   sql.SelectValues
}

// PMILocationEdges holds the relations/edges for other nodes in the graph.
type PMILocationEdges struct {
	// Subdistrict holds the value of the subdistrict edge.
	Subdistrict *Subdistrict `json:"subdistrict,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubdistrictOrErr returns the Subdistrict value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PMILocationEdges) SubdistrictOrErr() (*Subdistrict, error) {
	if e.Subdistrict != nil {
		return e.Subdistrict, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subdistrict.Label}
	}
	return nil, &NotLoadedError{edge: "subdistrict"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PMILocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pmilocation.FieldLatLng:
			values[i] = new(schema.GeoPoint)
		case pmilocation.FieldCreatedAt, pmilocation.FieldUpdatedAt, pmilocation.FieldDeletedAt, pmilocation.FieldBedCapacities:
			values[i] = new(sql.NullInt64)
		case pmilocation.FieldName, pmilocation.FieldStreet, pmilocation.FieldEmail, pmilocation.FieldDialCode, pmilocation.FieldPhoneNumber:
			values[i] = new(sql.NullString)
		case pmilocation.FieldOpensAt, pmilocation.FieldClosesAt:
			values[i] = new(sql.NullTime)
		case pmilocation.FieldID:
			values[i] = new(uuid.UUID)
		case pmilocation.ForeignKeys[0]: // subdistrict_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PMILocation fields.
func (_m *PMILocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pmilocation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pmilocation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case pmilocation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Int64
			}
		case pmilocation.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Int64
			}
		case pmilocation.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case pmilocation.FieldBedCapacities:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bed_capacities", values[i])
			} else if value.Valid {
				_m.BedCapacities = int16(value.Int64)
			}
		case pmilocation.FieldLatLng:
			if value, ok := values[i].(*schema.GeoPoint); !ok {
				return fmt.Errorf("unexpected type %T for field lat_lng", values[i])
			} else if value != nil {
				_m.LatLng = value
			}
		case pmilocation.FieldStreet:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field street", values[i])
			} else if value.Valid {
				_m.Street = value.String
			}
		case pmilocation.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case pmilocation.FieldDialCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dial_code", values[i])
			} else if value.Valid {
				_m.DialCode = value.String
			}
		case pmilocation.FieldPhoneNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone_number", values[i])
			} else if value.Valid {
				_m.PhoneNumber = value.String
			}
		case pmilocation.FieldOpensAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opens_at", values[i])
			} else if value.Valid {
				_m.OpensAt = value.Time
			}
		case pmilocation.FieldClosesAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closes_at", values[i])
			} else if value.Valid {
				_m.ClosesAt = value.Time
			}
		case pmilocation.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field subdistrict_id", values[i])
			} else if value.Valid {
				_m.subdistrict_id = new(uuid.UUID)
				*_m.subdistrict_id = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PMILocation.
// This includes values selected through modifiers, order, etc.
func (_m *PMILocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubdistrict queries the "subdistrict" edge of the PMILocation entity.
func (_m *PMILocation) QuerySubdistrict() *SubdistrictQuery {
	return NewPMILocationClient(_m.config).QuerySubdistrict(_m)
}

// Update returns a builder for updating this PMILocation.
// Note that you need to call PMILocation.Unwrap() before calling this method if this PMILocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PMILocation) Update() *PMILocationUpdateOne {
	return NewPMILocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PMILocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PMILocation) Unwrap() *PMILocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PMILocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PMILocation) String() string {
	var builder strings.Builder
	builder.WriteString("PMILocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("bed_capacities=")
	builder.WriteString(fmt.Sprintf("%v", _m.BedCapacities))
	builder.WriteString(", ")
	builder.WriteString("lat_lng=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatLng))
	builder.WriteString(", ")
	builder.WriteString("street=")
	builder.WriteString(_m.Street)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("dial_code=")
	builder.WriteString(_m.DialCode)
	builder.WriteString(", ")
	builder.WriteString("phone_number=")
	builder.WriteString(_m.PhoneNumber)
	builder.WriteString(", ")
	builder.WriteString("opens_at=")
	builder.WriteString(_m.OpensAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("closes_at=")
	builder.WriteString(_m.ClosesAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PMILocations is a parsable slice of PMILocation.
type PMILocations []*PMILocation
