// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sembraniteam/setetes/internal/ent/province"
)

// Province is the model entity for the Province schema.
type Province struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// BpsCode holds the value of the "bps_code" field.
	BpsCode string `json:"bps_code"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProvinceQuery when eager-loading is set.
	Edges        ProvinceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProvinceEdges holds the relations/edges for other nodes in the graph.
type ProvinceEdges struct {
	// City holds the value of the city edge.
	City []*City `json:"city,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CityOrErr returns the City value or an error if the edge
// was not loaded in eager-loading.
func (e ProvinceEdges) CityOrErr() ([]*City, error) {
	if e.loadedTypes[0] {
		return e.City, nil
	}
	return nil, &NotLoadedError{edge: "city"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Province) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case province.FieldBpsCode, province.FieldName:
			values[i] = new(sql.NullString)
		case province.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Province fields.
func (_m *Province) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case province.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case province.FieldBpsCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bps_code", values[i])
			} else if value.Valid {
				_m.BpsCode = value.String
			}
		case province.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Province.
// This includes values selected through modifiers, order, etc.
func (_m *Province) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCity queries the "city" edge of the Province entity.
func (_m *Province) QueryCity() *CityQuery {
	return NewProvinceClient(_m.config).QueryCity(_m)
}

// Update returns a builder for updating this Province.
// Note that you need to call Province.Unwrap() before calling this method if this Province
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Province) Update() *ProvinceUpdateOne {
	return NewProvinceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Province entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Province) Unwrap() *Province {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Province is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Province) String() string {
	var builder strings.Builder
	builder.WriteString("Province(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bps_code=")
	builder.WriteString(_m.BpsCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Provinces is a parsable slice of Province.
type Provinces []*Province
