// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/city"
	"github.com/megalodev/setetes/internal/ent/province"
)

// ProvinceCreate is the builder for creating a Province entity.
type ProvinceCreate struct {
	config
	mutation *ProvinceMutation
	hooks    []Hook
}

// SetBpsCode sets the "bps_code" field.
func (_c *ProvinceCreate) SetBpsCode(v string) *ProvinceCreate {
	_c.mutation.SetBpsCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProvinceCreate) SetName(v string) *ProvinceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ProvinceCreate) SetID(v uuid.UUID) *ProvinceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCityID sets the "city" edge to the City entity by ID.
func (_c *ProvinceCreate) SetCityID(id uuid.UUID) *ProvinceCreate {
	_c.mutation.SetCityID(id)
	return _c
}

// SetCity sets the "city" edge to the City entity.
func (_c *ProvinceCreate) SetCity(v *City) *ProvinceCreate {
	return _c.SetCityID(v.ID)
}

// Mutation returns the ProvinceMutation object of the builder.
func (_c *ProvinceCreate) Mutation() *ProvinceMutation {
	return _c.mutation
}

// Save creates the Province in the database.
func (_c *ProvinceCreate) Save(ctx context.Context) (*Province, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProvinceCreate) SaveX(ctx context.Context) *Province {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProvinceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProvinceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProvinceCreate) check() error {
	if _, ok := _c.mutation.BpsCode(); !ok {
		return &ValidationError{Name: "bps_code", err: errors.New(`ent: missing required field "Province.bps_code"`)}
	}
	if v, ok := _c.mutation.BpsCode(); ok {
		if err := province.BpsCodeValidator(v); err != nil {
			return &ValidationError{Name: "bps_code", err: fmt.Errorf(`ent: validator failed for field "Province.bps_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Province.name"`)}
	}
	if len(_c.mutation.CityIDs()) == 0 {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required edge "Province.city"`)}
	}
	return nil
}

func (_c *ProvinceCreate) sqlSave(ctx context.Context) (*Province, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProvinceCreate) createSpec() (*Province, *sqlgraph.CreateSpec) {
	var (
		_node = &Province{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(province.Table, sqlgraph.NewFieldSpec(province.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BpsCode(); ok {
		_spec.SetField(province.FieldBpsCode, field.TypeString, value)
		_node.BpsCode = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(province.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.CityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   province.CityTable,
			Columns: []string{province.CityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.province_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProvinceCreateBulk is the builder for creating many Province entities in bulk.
type ProvinceCreateBulk struct {
	config
	err      error
	builders []*ProvinceCreate
}

// Save creates the Province entities in the database.
func (_c *ProvinceCreateBulk) Save(ctx context.Context) ([]*Province, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Province, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProvinceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProvinceCreateBulk) SaveX(ctx context.Context) []*Province {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProvinceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProvinceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
