// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/megalodev/setetes/internal/ent/account"
	"github.com/megalodev/setetes/internal/ent/bloodtype"
	"github.com/megalodev/setetes/internal/ent/city"
	"github.com/megalodev/setetes/internal/ent/district"
	"github.com/megalodev/setetes/internal/ent/otp"
	"github.com/megalodev/setetes/internal/ent/password"
	"github.com/megalodev/setetes/internal/ent/pmilocation"
	"github.com/megalodev/setetes/internal/ent/province"
	"github.com/megalodev/setetes/internal/ent/schema"
	"github.com/megalodev/setetes/internal/ent/subdistrict"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountMixinFields0[1].Descriptor()
	// account.CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	account.CreatedAtValidator = accountDescCreatedAt.Validators[0].(func(int64) error)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountMixinFields0[2].Descriptor()
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() int64)
	// account.UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	account.UpdatedAtValidator = accountDescUpdatedAt.Validators[0].(func(int64) error)
	// accountDescDeletedAt is the schema descriptor for deleted_at field.
	accountDescDeletedAt := accountMixinFields0[3].Descriptor()
	// account.DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	account.DeletedAtValidator = accountDescDeletedAt.Validators[0].(func(int64) error)
	// accountDescNationalIDHash is the schema descriptor for national_id_hash field.
	accountDescNationalIDHash := accountFields[0].Descriptor()
	// account.NationalIDHashValidator is a validator for the "national_id_hash" field. It is called by the builders before save.
	account.NationalIDHashValidator = func() func(string) error {
		validators := accountDescNationalIDHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(national_id_hash string) error {
			for _, fn := range fns {
				if err := fn(national_id_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescNationalIDMasked is the schema descriptor for national_id_masked field.
	accountDescNationalIDMasked := accountFields[1].Descriptor()
	// account.NationalIDMaskedValidator is a validator for the "national_id_masked" field. It is called by the builders before save.
	account.NationalIDMaskedValidator = func() func(string) error {
		validators := accountDescNationalIDMasked.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(national_id_masked string) error {
			for _, fn := range fns {
				if err := fn(national_id_masked); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescFullName is the schema descriptor for full_name field.
	accountDescFullName := accountFields[2].Descriptor()
	// account.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	account.FullNameValidator = func() func(string) error {
		validators := accountDescFullName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(full_name string) error {
			for _, fn := range fns {
				if err := fn(full_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescEmail is the schema descriptor for email field.
	accountDescEmail := accountFields[4].Descriptor()
	// account.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	account.EmailValidator = func() func(string) error {
		validators := accountDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescCountryIsoCode is the schema descriptor for country_iso_code field.
	accountDescCountryIsoCode := accountFields[5].Descriptor()
	// account.CountryIsoCodeValidator is a validator for the "country_iso_code" field. It is called by the builders before save.
	account.CountryIsoCodeValidator = func() func(string) error {
		validators := accountDescCountryIsoCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(country_iso_code string) error {
			for _, fn := range fns {
				if err := fn(country_iso_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescDialCode is the schema descriptor for dial_code field.
	accountDescDialCode := accountFields[6].Descriptor()
	// account.DialCodeValidator is a validator for the "dial_code" field. It is called by the builders before save.
	account.DialCodeValidator = func() func(string) error {
		validators := accountDescDialCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(dial_code string) error {
			for _, fn := range fns {
				if err := fn(dial_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescPhoneNumber is the schema descriptor for phone_number field.
	accountDescPhoneNumber := accountFields[7].Descriptor()
	// account.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	account.PhoneNumberValidator = func() func(string) error {
		validators := accountDescPhoneNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone_number string) error {
			for _, fn := range fns {
				if err := fn(phone_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescActivated is the schema descriptor for activated field.
	accountDescActivated := accountFields[8].Descriptor()
	// account.DefaultActivated holds the default value on creation for the activated field.
	account.DefaultActivated = accountDescActivated.Default.(bool)
	// accountDescLocked is the schema descriptor for locked field.
	accountDescLocked := accountFields[9].Descriptor()
	// account.DefaultLocked holds the default value on creation for the locked field.
	account.DefaultLocked = accountDescLocked.Default.(bool)
	// accountDescTempLockedAt is the schema descriptor for temp_locked_at field.
	accountDescTempLockedAt := accountFields[10].Descriptor()
	// account.TempLockedAtValidator is a validator for the "temp_locked_at" field. It is called by the builders before save.
	account.TempLockedAtValidator = accountDescTempLockedAt.Validators[0].(func(int64) error)
	bloodtypeMixin := schema.BloodType{}.Mixin()
	bloodtypeMixinFields0 := bloodtypeMixin[0].Fields()
	_ = bloodtypeMixinFields0
	bloodtypeFields := schema.BloodType{}.Fields()
	_ = bloodtypeFields
	// bloodtypeDescCreatedAt is the schema descriptor for created_at field.
	bloodtypeDescCreatedAt := bloodtypeMixinFields0[1].Descriptor()
	// bloodtype.CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	bloodtype.CreatedAtValidator = bloodtypeDescCreatedAt.Validators[0].(func(int64) error)
	// bloodtypeDescUpdatedAt is the schema descriptor for updated_at field.
	bloodtypeDescUpdatedAt := bloodtypeMixinFields0[2].Descriptor()
	// bloodtype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bloodtype.UpdateDefaultUpdatedAt = bloodtypeDescUpdatedAt.UpdateDefault.(func() int64)
	// bloodtype.UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	bloodtype.UpdatedAtValidator = bloodtypeDescUpdatedAt.Validators[0].(func(int64) error)
	// bloodtypeDescDeletedAt is the schema descriptor for deleted_at field.
	bloodtypeDescDeletedAt := bloodtypeMixinFields0[3].Descriptor()
	// bloodtype.DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	bloodtype.DeletedAtValidator = bloodtypeDescDeletedAt.Validators[0].(func(int64) error)
	cityFields := schema.City{}.Fields()
	_ = cityFields
	// cityDescBpsCode is the schema descriptor for bps_code field.
	cityDescBpsCode := cityFields[1].Descriptor()
	// city.BpsCodeValidator is a validator for the "bps_code" field. It is called by the builders before save.
	city.BpsCodeValidator = cityDescBpsCode.Validators[0].(func(string) error)
	districtFields := schema.District{}.Fields()
	_ = districtFields
	// districtDescBpsCode is the schema descriptor for bps_code field.
	districtDescBpsCode := districtFields[1].Descriptor()
	// district.BpsCodeValidator is a validator for the "bps_code" field. It is called by the builders before save.
	district.BpsCodeValidator = districtDescBpsCode.Validators[0].(func(string) error)
	otpMixin := schema.OTP{}.Mixin()
	otpMixinFields0 := otpMixin[0].Fields()
	_ = otpMixinFields0
	otpFields := schema.OTP{}.Fields()
	_ = otpFields
	// otpDescCreatedAt is the schema descriptor for created_at field.
	otpDescCreatedAt := otpMixinFields0[1].Descriptor()
	// otp.CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	otp.CreatedAtValidator = otpDescCreatedAt.Validators[0].(func(int64) error)
	// otpDescUpdatedAt is the schema descriptor for updated_at field.
	otpDescUpdatedAt := otpMixinFields0[2].Descriptor()
	// otp.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	otp.UpdateDefaultUpdatedAt = otpDescUpdatedAt.UpdateDefault.(func() int64)
	// otp.UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	otp.UpdatedAtValidator = otpDescUpdatedAt.Validators[0].(func(int64) error)
	// otpDescDeletedAt is the schema descriptor for deleted_at field.
	otpDescDeletedAt := otpMixinFields0[3].Descriptor()
	// otp.DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	otp.DeletedAtValidator = otpDescDeletedAt.Validators[0].(func(int64) error)
	// otpDescCodeHash is the schema descriptor for code_hash field.
	otpDescCodeHash := otpFields[0].Descriptor()
	// otp.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	otp.CodeHashValidator = func() func(string) error {
		validators := otpDescCodeHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code_hash string) error {
			for _, fn := range fns {
				if err := fn(code_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// otpDescExpiredAt is the schema descriptor for expired_at field.
	otpDescExpiredAt := otpFields[2].Descriptor()
	// otp.ExpiredAtValidator is a validator for the "expired_at" field. It is called by the builders before save.
	otp.ExpiredAtValidator = otpDescExpiredAt.Validators[0].(func(int64) error)
	pmilocationMixin := schema.PMILocation{}.Mixin()
	pmilocationMixinFields0 := pmilocationMixin[0].Fields()
	_ = pmilocationMixinFields0
	pmilocationFields := schema.PMILocation{}.Fields()
	_ = pmilocationFields
	// pmilocationDescCreatedAt is the schema descriptor for created_at field.
	pmilocationDescCreatedAt := pmilocationMixinFields0[1].Descriptor()
	// pmilocation.CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	pmilocation.CreatedAtValidator = pmilocationDescCreatedAt.Validators[0].(func(int64) error)
	// pmilocationDescUpdatedAt is the schema descriptor for updated_at field.
	pmilocationDescUpdatedAt := pmilocationMixinFields0[2].Descriptor()
	// pmilocation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pmilocation.UpdateDefaultUpdatedAt = pmilocationDescUpdatedAt.UpdateDefault.(func() int64)
	// pmilocation.UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	pmilocation.UpdatedAtValidator = pmilocationDescUpdatedAt.Validators[0].(func(int64) error)
	// pmilocationDescDeletedAt is the schema descriptor for deleted_at field.
	pmilocationDescDeletedAt := pmilocationMixinFields0[3].Descriptor()
	// pmilocation.DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	pmilocation.DeletedAtValidator = pmilocationDescDeletedAt.Validators[0].(func(int64) error)
	// pmilocationDescName is the schema descriptor for name field.
	pmilocationDescName := pmilocationFields[0].Descriptor()
	// pmilocation.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pmilocation.NameValidator = func() func(string) error {
		validators := pmilocationDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pmilocationDescBedCapacities is the schema descriptor for bed_capacities field.
	pmilocationDescBedCapacities := pmilocationFields[1].Descriptor()
	// pmilocation.DefaultBedCapacities holds the default value on creation for the bed_capacities field.
	pmilocation.DefaultBedCapacities = pmilocationDescBedCapacities.Default.(int16)
	// pmilocation.BedCapacitiesValidator is a validator for the "bed_capacities" field. It is called by the builders before save.
	pmilocation.BedCapacitiesValidator = pmilocationDescBedCapacities.Validators[0].(func(int16) error)
	// pmilocationDescStreet is the schema descriptor for street field.
	pmilocationDescStreet := pmilocationFields[3].Descriptor()
	// pmilocation.StreetValidator is a validator for the "street" field. It is called by the builders before save.
	pmilocation.StreetValidator = pmilocationDescStreet.Validators[0].(func(string) error)
	// pmilocationDescEmail is the schema descriptor for email field.
	pmilocationDescEmail := pmilocationFields[4].Descriptor()
	// pmilocation.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	pmilocation.EmailValidator = func() func(string) error {
		validators := pmilocationDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// pmilocationDescPhoneNumber is the schema descriptor for phone_number field.
	pmilocationDescPhoneNumber := pmilocationFields[6].Descriptor()
	// pmilocation.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	pmilocation.PhoneNumberValidator = func() func(string) error {
		validators := pmilocationDescPhoneNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone_number string) error {
			for _, fn := range fns {
				if err := fn(phone_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	passwordMixin := schema.Password{}.Mixin()
	passwordMixinFields0 := passwordMixin[0].Fields()
	_ = passwordMixinFields0
	passwordFields := schema.Password{}.Fields()
	_ = passwordFields
	// passwordDescCreatedAt is the schema descriptor for created_at field.
	passwordDescCreatedAt := passwordMixinFields0[1].Descriptor()
	// password.CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	password.CreatedAtValidator = passwordDescCreatedAt.Validators[0].(func(int64) error)
	// passwordDescUpdatedAt is the schema descriptor for updated_at field.
	passwordDescUpdatedAt := passwordMixinFields0[2].Descriptor()
	// password.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	password.UpdateDefaultUpdatedAt = passwordDescUpdatedAt.UpdateDefault.(func() int64)
	// password.UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	password.UpdatedAtValidator = passwordDescUpdatedAt.Validators[0].(func(int64) error)
	// passwordDescDeletedAt is the schema descriptor for deleted_at field.
	passwordDescDeletedAt := passwordMixinFields0[3].Descriptor()
	// password.DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	password.DeletedAtValidator = passwordDescDeletedAt.Validators[0].(func(int64) error)
	provinceFields := schema.Province{}.Fields()
	_ = provinceFields
	// provinceDescBpsCode is the schema descriptor for bps_code field.
	provinceDescBpsCode := provinceFields[1].Descriptor()
	// province.BpsCodeValidator is a validator for the "bps_code" field. It is called by the builders before save.
	province.BpsCodeValidator = provinceDescBpsCode.Validators[0].(func(string) error)
	subdistrictFields := schema.Subdistrict{}.Fields()
	_ = subdistrictFields
	// subdistrictDescBpsCode is the schema descriptor for bps_code field.
	subdistrictDescBpsCode := subdistrictFields[1].Descriptor()
	// subdistrict.BpsCodeValidator is a validator for the "bps_code" field. It is called by the builders before save.
	subdistrict.BpsCodeValidator = subdistrictDescBpsCode.Validators[0].(func(string) error)
	// subdistrictDescPostalCode is the schema descriptor for postal_code field.
	subdistrictDescPostalCode := subdistrictFields[2].Descriptor()
	// subdistrict.PostalCodeValidator is a validator for the "postal_code" field. It is called by the builders before save.
	subdistrict.PostalCodeValidator = subdistrictDescPostalCode.Validators[0].(func(string) error)
}
