// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sembraniteam/setetes/internal/ent/district"
	"github.com/sembraniteam/setetes/internal/ent/pmilocation"
	"github.com/sembraniteam/setetes/internal/ent/predicate"
	"github.com/sembraniteam/setetes/internal/ent/subdistrict"
)

// SubdistrictUpdate is the builder for updating Subdistrict entities.
type SubdistrictUpdate struct {
	config
	hooks    []Hook
	mutation *SubdistrictMutation
}

// Where appends a list predicates to the SubdistrictUpdate builder.
func (_u *SubdistrictUpdate) Where(ps ...predicate.Subdistrict) *SubdistrictUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBpsCode sets the "bps_code" field.
func (_u *SubdistrictUpdate) SetBpsCode(v string) *SubdistrictUpdate {
	_u.mutation.SetBpsCode(v)
	return _u
}

// SetNillableBpsCode sets the "bps_code" field if the given value is not nil.
func (_u *SubdistrictUpdate) SetNillableBpsCode(v *string) *SubdistrictUpdate {
	if v != nil {
		_u.SetBpsCode(*v)
	}
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *SubdistrictUpdate) SetPostalCode(v string) *SubdistrictUpdate {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *SubdistrictUpdate) SetNillablePostalCode(v *string) *SubdistrictUpdate {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SubdistrictUpdate) SetName(v string) *SubdistrictUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubdistrictUpdate) SetNillableName(v *string) *SubdistrictUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDistrictID sets the "district" edge to the District entity by ID.
func (_u *SubdistrictUpdate) SetDistrictID(id uuid.UUID) *SubdistrictUpdate {
	_u.mutation.SetDistrictID(id)
	return _u
}

// SetDistrict sets the "district" edge to the District entity.
func (_u *SubdistrictUpdate) SetDistrict(v *District) *SubdistrictUpdate {
	return _u.SetDistrictID(v.ID)
}

// AddPmiLocationIDs adds the "pmi_location" edge to the PMILocation entity by IDs.
func (_u *SubdistrictUpdate) AddPmiLocationIDs(ids ...uuid.UUID) *SubdistrictUpdate {
	_u.mutation.AddPmiLocationIDs(ids...)
	return _u
}

// AddPmiLocation adds the "pmi_location" edges to the PMILocation entity.
func (_u *SubdistrictUpdate) AddPmiLocation(v ...*PMILocation) *SubdistrictUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPmiLocationIDs(ids...)
}

// Mutation returns the SubdistrictMutation object of the builder.
func (_u *SubdistrictUpdate) Mutation() *SubdistrictMutation {
	return _u.mutation
}

// ClearDistrict clears the "district" edge to the District entity.
func (_u *SubdistrictUpdate) ClearDistrict() *SubdistrictUpdate {
	_u.mutation.ClearDistrict()
	return _u
}

// ClearPmiLocation clears all "pmi_location" edges to the PMILocation entity.
func (_u *SubdistrictUpdate) ClearPmiLocation() *SubdistrictUpdate {
	_u.mutation.ClearPmiLocation()
	return _u
}

// RemovePmiLocationIDs removes the "pmi_location" edge to PMILocation entities by IDs.
func (_u *SubdistrictUpdate) RemovePmiLocationIDs(ids ...uuid.UUID) *SubdistrictUpdate {
	_u.mutation.RemovePmiLocationIDs(ids...)
	return _u
}

// RemovePmiLocation removes "pmi_location" edges to PMILocation entities.
func (_u *SubdistrictUpdate) RemovePmiLocation(v ...*PMILocation) *SubdistrictUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePmiLocationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubdistrictUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubdistrictUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubdistrictUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubdistrictUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubdistrictUpdate) check() error {
	if v, ok := _u.mutation.BpsCode(); ok {
		if err := subdistrict.BpsCodeValidator(v); err != nil {
			return &ValidationError{Name: "bps_code", err: fmt.Errorf(`ent: validator failed for field "Subdistrict.bps_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := subdistrict.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Subdistrict.postal_code": %w`, err)}
		}
	}
	if _u.mutation.DistrictCleared() && len(_u.mutation.DistrictIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subdistrict.district"`)
	}
	return nil
}

func (_u *SubdistrictUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subdistrict.Table, subdistrict.Columns, sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BpsCode(); ok {
		_spec.SetField(subdistrict.FieldBpsCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(subdistrict.FieldPostalCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subdistrict.FieldName, field.TypeString, value)
	}
	if _u.mutation.DistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subdistrict.DistrictTable,
			Columns: []string{subdistrict.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subdistrict.DistrictTable,
			Columns: []string{subdistrict.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PmiLocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.PmiLocationTable,
			Columns: []string{subdistrict.PmiLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPmiLocationIDs(); len(nodes) > 0 && !_u.mutation.PmiLocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.PmiLocationTable,
			Columns: []string{subdistrict.PmiLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PmiLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.PmiLocationTable,
			Columns: []string{subdistrict.PmiLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subdistrict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubdistrictUpdateOne is the builder for updating a single Subdistrict entity.
type SubdistrictUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubdistrictMutation
}

// SetBpsCode sets the "bps_code" field.
func (_u *SubdistrictUpdateOne) SetBpsCode(v string) *SubdistrictUpdateOne {
	_u.mutation.SetBpsCode(v)
	return _u
}

// SetNillableBpsCode sets the "bps_code" field if the given value is not nil.
func (_u *SubdistrictUpdateOne) SetNillableBpsCode(v *string) *SubdistrictUpdateOne {
	if v != nil {
		_u.SetBpsCode(*v)
	}
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *SubdistrictUpdateOne) SetPostalCode(v string) *SubdistrictUpdateOne {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *SubdistrictUpdateOne) SetNillablePostalCode(v *string) *SubdistrictUpdateOne {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SubdistrictUpdateOne) SetName(v string) *SubdistrictUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubdistrictUpdateOne) SetNillableName(v *string) *SubdistrictUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDistrictID sets the "district" edge to the District entity by ID.
func (_u *SubdistrictUpdateOne) SetDistrictID(id uuid.UUID) *SubdistrictUpdateOne {
	_u.mutation.SetDistrictID(id)
	return _u
}

// SetDistrict sets the "district" edge to the District entity.
func (_u *SubdistrictUpdateOne) SetDistrict(v *District) *SubdistrictUpdateOne {
	return _u.SetDistrictID(v.ID)
}

// AddPmiLocationIDs adds the "pmi_location" edge to the PMILocation entity by IDs.
func (_u *SubdistrictUpdateOne) AddPmiLocationIDs(ids ...uuid.UUID) *SubdistrictUpdateOne {
	_u.mutation.AddPmiLocationIDs(ids...)
	return _u
}

// AddPmiLocation adds the "pmi_location" edges to the PMILocation entity.
func (_u *SubdistrictUpdateOne) AddPmiLocation(v ...*PMILocation) *SubdistrictUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPmiLocationIDs(ids...)
}

// Mutation returns the SubdistrictMutation object of the builder.
func (_u *SubdistrictUpdateOne) Mutation() *SubdistrictMutation {
	return _u.mutation
}

// ClearDistrict clears the "district" edge to the District entity.
func (_u *SubdistrictUpdateOne) ClearDistrict() *SubdistrictUpdateOne {
	_u.mutation.ClearDistrict()
	return _u
}

// ClearPmiLocation clears all "pmi_location" edges to the PMILocation entity.
func (_u *SubdistrictUpdateOne) ClearPmiLocation() *SubdistrictUpdateOne {
	_u.mutation.ClearPmiLocation()
	return _u
}

// RemovePmiLocationIDs removes the "pmi_location" edge to PMILocation entities by IDs.
func (_u *SubdistrictUpdateOne) RemovePmiLocationIDs(ids ...uuid.UUID) *SubdistrictUpdateOne {
	_u.mutation.RemovePmiLocationIDs(ids...)
	return _u
}

// RemovePmiLocation removes "pmi_location" edges to PMILocation entities.
func (_u *SubdistrictUpdateOne) RemovePmiLocation(v ...*PMILocation) *SubdistrictUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePmiLocationIDs(ids...)
}

// Where appends a list predicates to the SubdistrictUpdate builder.
func (_u *SubdistrictUpdateOne) Where(ps ...predicate.Subdistrict) *SubdistrictUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubdistrictUpdateOne) Select(field string, fields ...string) *SubdistrictUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subdistrict entity.
func (_u *SubdistrictUpdateOne) Save(ctx context.Context) (*Subdistrict, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubdistrictUpdateOne) SaveX(ctx context.Context) *Subdistrict {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubdistrictUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubdistrictUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubdistrictUpdateOne) check() error {
	if v, ok := _u.mutation.BpsCode(); ok {
		if err := subdistrict.BpsCodeValidator(v); err != nil {
			return &ValidationError{Name: "bps_code", err: fmt.Errorf(`ent: validator failed for field "Subdistrict.bps_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := subdistrict.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Subdistrict.postal_code": %w`, err)}
		}
	}
	if _u.mutation.DistrictCleared() && len(_u.mutation.DistrictIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subdistrict.district"`)
	}
	return nil
}

func (_u *SubdistrictUpdateOne) sqlSave(ctx context.Context) (_node *Subdistrict, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subdistrict.Table, subdistrict.Columns, sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subdistrict.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subdistrict.FieldID)
		for _, f := range fields {
			if !subdistrict.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subdistrict.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BpsCode(); ok {
		_spec.SetField(subdistrict.FieldBpsCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(subdistrict.FieldPostalCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subdistrict.FieldName, field.TypeString, value)
	}
	if _u.mutation.DistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subdistrict.DistrictTable,
			Columns: []string{subdistrict.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subdistrict.DistrictTable,
			Columns: []string{subdistrict.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PmiLocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.PmiLocationTable,
			Columns: []string{subdistrict.PmiLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPmiLocationIDs(); len(nodes) > 0 && !_u.mutation.PmiLocationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.PmiLocationTable,
			Columns: []string{subdistrict.PmiLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PmiLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.PmiLocationTable,
			Columns: []string{subdistrict.PmiLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subdistrict{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subdistrict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
