// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/district"
	"github.com/megalodev/setetes/internal/ent/pmilocation"
	"github.com/megalodev/setetes/internal/ent/predicate"
	"github.com/megalodev/setetes/internal/ent/subdistrict"
)

// SubdistrictQuery is the builder for querying Subdistrict entities.
type SubdistrictQuery struct {
	config
	ctx             *QueryContext
	order           []subdistrict.OrderOption
	inters          []Interceptor
	predicates      []predicate.Subdistrict
	withDistrict    *DistrictQuery
	withPmiLocation *PMILocationQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubdistrictQuery builder.
func (_q *SubdistrictQuery) Where(ps ...predicate.Subdistrict) *SubdistrictQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubdistrictQuery) Limit(limit int) *SubdistrictQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubdistrictQuery) Offset(offset int) *SubdistrictQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubdistrictQuery) Unique(unique bool) *SubdistrictQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubdistrictQuery) Order(o ...subdistrict.OrderOption) *SubdistrictQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDistrict chains the current query on the "district" edge.
func (_q *SubdistrictQuery) QueryDistrict() *DistrictQuery {
	query := (&DistrictClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subdistrict.Table, subdistrict.FieldID, selector),
			sqlgraph.To(district.Table, district.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subdistrict.DistrictTable, subdistrict.DistrictColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPmiLocation chains the current query on the "pmi_location" edge.
func (_q *SubdistrictQuery) QueryPmiLocation() *PMILocationQuery {
	query := (&PMILocationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subdistrict.Table, subdistrict.FieldID, selector),
			sqlgraph.To(pmilocation.Table, pmilocation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subdistrict.PmiLocationTable, subdistrict.PmiLocationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Subdistrict entity from the query.
// Returns a *NotFoundError when no Subdistrict was found.
func (_q *SubdistrictQuery) First(ctx context.Context) (*Subdistrict, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subdistrict.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubdistrictQuery) FirstX(ctx context.Context) *Subdistrict {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Subdistrict ID from the query.
// Returns a *NotFoundError when no Subdistrict ID was found.
func (_q *SubdistrictQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subdistrict.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubdistrictQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Subdistrict entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Subdistrict entity is found.
// Returns a *NotFoundError when no Subdistrict entities are found.
func (_q *SubdistrictQuery) Only(ctx context.Context) (*Subdistrict, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subdistrict.Label}
	default:
		return nil, &NotSingularError{subdistrict.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubdistrictQuery) OnlyX(ctx context.Context) *Subdistrict {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Subdistrict ID in the query.
// Returns a *NotSingularError when more than one Subdistrict ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubdistrictQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subdistrict.Label}
	default:
		err = &NotSingularError{subdistrict.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubdistrictQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Subdistricts.
func (_q *SubdistrictQuery) All(ctx context.Context) ([]*Subdistrict, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Subdistrict, *SubdistrictQuery]()
	return withInterceptors[[]*Subdistrict](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubdistrictQuery) AllX(ctx context.Context) []*Subdistrict {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Subdistrict IDs.
func (_q *SubdistrictQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subdistrict.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubdistrictQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubdistrictQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubdistrictQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubdistrictQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubdistrictQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubdistrictQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubdistrictQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubdistrictQuery) Clone() *SubdistrictQuery {
	if _q == nil {
		return nil
	}
	return &SubdistrictQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]subdistrict.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.Subdistrict{}, _q.predicates...),
		withDistrict:    _q.withDistrict.Clone(),
		withPmiLocation: _q.withPmiLocation.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDistrict tells the query-builder to eager-load the nodes that are connected to
// the "district" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubdistrictQuery) WithDistrict(opts ...func(*DistrictQuery)) *SubdistrictQuery {
	query := (&DistrictClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDistrict = query
	return _q
}

// WithPmiLocation tells the query-builder to eager-load the nodes that are connected to
// the "pmi_location" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubdistrictQuery) WithPmiLocation(opts ...func(*PMILocationQuery)) *SubdistrictQuery {
	query := (&PMILocationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPmiLocation = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Subdistrict.Query().
//		GroupBy(subdistrict.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubdistrictQuery) GroupBy(field string, fields ...string) *SubdistrictGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubdistrictGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subdistrict.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at"`
//	}
//
//	client.Subdistrict.Query().
//		Select(subdistrict.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SubdistrictQuery) Select(fields ...string) *SubdistrictSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubdistrictSelect{SubdistrictQuery: _q}
	sbuild.label = subdistrict.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubdistrictSelect configured with the given aggregations.
func (_q *SubdistrictQuery) Aggregate(fns ...AggregateFunc) *SubdistrictSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubdistrictQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subdistrict.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubdistrictQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Subdistrict, error) {
	var (
		nodes       = []*Subdistrict{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withDistrict != nil,
			_q.withPmiLocation != nil,
		}
	)
	if _q.withPmiLocation != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, subdistrict.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Subdistrict).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Subdistrict{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDistrict; query != nil {
		if err := _q.loadDistrict(ctx, query, nodes,
			func(n *Subdistrict) { n.Edges.District = []*District{} },
			func(n *Subdistrict, e *District) { n.Edges.District = append(n.Edges.District, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPmiLocation; query != nil {
		if err := _q.loadPmiLocation(ctx, query, nodes, nil,
			func(n *Subdistrict, e *PMILocation) { n.Edges.PmiLocation = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubdistrictQuery) loadDistrict(ctx context.Context, query *DistrictQuery, nodes []*Subdistrict, init func(*Subdistrict), assign func(*Subdistrict, *District)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Subdistrict)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.District(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subdistrict.DistrictColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.district_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "district_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "district_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *SubdistrictQuery) loadPmiLocation(ctx context.Context, query *PMILocationQuery, nodes []*Subdistrict, init func(*Subdistrict), assign func(*Subdistrict, *PMILocation)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Subdistrict)
	for i := range nodes {
		if nodes[i].subdistrict_id == nil {
			continue
		}
		fk := *nodes[i].subdistrict_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(pmilocation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subdistrict_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SubdistrictQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubdistrictQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subdistrict.Table, subdistrict.Columns, sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subdistrict.FieldID)
		for i := range fields {
			if fields[i] != subdistrict.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubdistrictQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subdistrict.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subdistrict.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubdistrictGroupBy is the group-by builder for Subdistrict entities.
type SubdistrictGroupBy struct {
	selector
	build *SubdistrictQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubdistrictGroupBy) Aggregate(fns ...AggregateFunc) *SubdistrictGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubdistrictGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubdistrictQuery, *SubdistrictGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubdistrictGroupBy) sqlScan(ctx context.Context, root *SubdistrictQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubdistrictSelect is the builder for selecting fields of Subdistrict entities.
type SubdistrictSelect struct {
	*SubdistrictQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubdistrictSelect) Aggregate(fns ...AggregateFunc) *SubdistrictSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubdistrictSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubdistrictQuery, *SubdistrictSelect](ctx, _s.SubdistrictQuery, _s, _s.inters, v)
}

func (_s *SubdistrictSelect) sqlScan(ctx context.Context, root *SubdistrictQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
