// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/internal/ent/district"
	"github.com/megalodev/setetes/internal/ent/pmilocation"
	"github.com/megalodev/setetes/internal/ent/subdistrict"
)

// SubdistrictCreate is the builder for creating a Subdistrict entity.
type SubdistrictCreate struct {
	config
	mutation *SubdistrictMutation
	hooks    []Hook
}

// SetBpsCode sets the "bps_code" field.
func (_c *SubdistrictCreate) SetBpsCode(v string) *SubdistrictCreate {
	_c.mutation.SetBpsCode(v)
	return _c
}

// SetPostalCode sets the "postal_code" field.
func (_c *SubdistrictCreate) SetPostalCode(v string) *SubdistrictCreate {
	_c.mutation.SetPostalCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SubdistrictCreate) SetName(v string) *SubdistrictCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SubdistrictCreate) SetID(v uuid.UUID) *SubdistrictCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDistrictID sets the "district" edge to the District entity by ID.
func (_c *SubdistrictCreate) SetDistrictID(id uuid.UUID) *SubdistrictCreate {
	_c.mutation.SetDistrictID(id)
	return _c
}

// SetDistrict sets the "district" edge to the District entity.
func (_c *SubdistrictCreate) SetDistrict(v *District) *SubdistrictCreate {
	return _c.SetDistrictID(v.ID)
}

// AddPmiLocationIDs adds the "pmi_location" edge to the PMILocation entity by IDs.
func (_c *SubdistrictCreate) AddPmiLocationIDs(ids ...uuid.UUID) *SubdistrictCreate {
	_c.mutation.AddPmiLocationIDs(ids...)
	return _c
}

// AddPmiLocation adds the "pmi_location" edges to the PMILocation entity.
func (_c *SubdistrictCreate) AddPmiLocation(v ...*PMILocation) *SubdistrictCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPmiLocationIDs(ids...)
}

// Mutation returns the SubdistrictMutation object of the builder.
func (_c *SubdistrictCreate) Mutation() *SubdistrictMutation {
	return _c.mutation
}

// Save creates the Subdistrict in the database.
func (_c *SubdistrictCreate) Save(ctx context.Context) (*Subdistrict, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubdistrictCreate) SaveX(ctx context.Context) *Subdistrict {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubdistrictCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubdistrictCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubdistrictCreate) check() error {
	if _, ok := _c.mutation.BpsCode(); !ok {
		return &ValidationError{Name: "bps_code", err: errors.New(`ent: missing required field "Subdistrict.bps_code"`)}
	}
	if v, ok := _c.mutation.BpsCode(); ok {
		if err := subdistrict.BpsCodeValidator(v); err != nil {
			return &ValidationError{Name: "bps_code", err: fmt.Errorf(`ent: validator failed for field "Subdistrict.bps_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PostalCode(); !ok {
		return &ValidationError{Name: "postal_code", err: errors.New(`ent: missing required field "Subdistrict.postal_code"`)}
	}
	if v, ok := _c.mutation.PostalCode(); ok {
		if err := subdistrict.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Subdistrict.postal_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Subdistrict.name"`)}
	}
	if len(_c.mutation.DistrictIDs()) == 0 {
		return &ValidationError{Name: "district", err: errors.New(`ent: missing required edge "Subdistrict.district"`)}
	}
	return nil
}

func (_c *SubdistrictCreate) sqlSave(ctx context.Context) (*Subdistrict, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubdistrictCreate) createSpec() (*Subdistrict, *sqlgraph.CreateSpec) {
	var (
		_node = &Subdistrict{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subdistrict.Table, sqlgraph.NewFieldSpec(subdistrict.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BpsCode(); ok {
		_spec.SetField(subdistrict.FieldBpsCode, field.TypeString, value)
		_node.BpsCode = value
	}
	if value, ok := _c.mutation.PostalCode(); ok {
		_spec.SetField(subdistrict.FieldPostalCode, field.TypeString, value)
		_node.PostalCode = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subdistrict.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subdistrict.DistrictTable,
			Columns: []string{subdistrict.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.district_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PmiLocationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subdistrict.PmiLocationTable,
			Columns: []string{subdistrict.PmiLocationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pmilocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubdistrictCreateBulk is the builder for creating many Subdistrict entities in bulk.
type SubdistrictCreateBulk struct {
	config
	err      error
	builders []*SubdistrictCreate
}

// Save creates the Subdistrict entities in the database.
func (_c *SubdistrictCreateBulk) Save(ctx context.Context) ([]*Subdistrict, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Subdistrict, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubdistrictMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubdistrictCreateBulk) SaveX(ctx context.Context) []*Subdistrict {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubdistrictCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubdistrictCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
