// Code generated by ent, DO NOT EDIT.

package subdistrict

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sembraniteam/setetes/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLTE(FieldID, id))
}

// BpsCode applies equality check predicate on the "bps_code" field. It's identical to BpsCodeEQ.
func BpsCode(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldBpsCode, v))
}

// PostalCode applies equality check predicate on the "postal_code" field. It's identical to PostalCodeEQ.
func PostalCode(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldPostalCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldName, v))
}

// BpsCodeEQ applies the EQ predicate on the "bps_code" field.
func BpsCodeEQ(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldBpsCode, v))
}

// BpsCodeNEQ applies the NEQ predicate on the "bps_code" field.
func BpsCodeNEQ(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNEQ(FieldBpsCode, v))
}

// BpsCodeIn applies the In predicate on the "bps_code" field.
func BpsCodeIn(vs ...string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldIn(FieldBpsCode, vs...))
}

// BpsCodeNotIn applies the NotIn predicate on the "bps_code" field.
func BpsCodeNotIn(vs ...string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNotIn(FieldBpsCode, vs...))
}

// BpsCodeGT applies the GT predicate on the "bps_code" field.
func BpsCodeGT(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGT(FieldBpsCode, v))
}

// BpsCodeGTE applies the GTE predicate on the "bps_code" field.
func BpsCodeGTE(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGTE(FieldBpsCode, v))
}

// BpsCodeLT applies the LT predicate on the "bps_code" field.
func BpsCodeLT(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLT(FieldBpsCode, v))
}

// BpsCodeLTE applies the LTE predicate on the "bps_code" field.
func BpsCodeLTE(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLTE(FieldBpsCode, v))
}

// BpsCodeContains applies the Contains predicate on the "bps_code" field.
func BpsCodeContains(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldContains(FieldBpsCode, v))
}

// BpsCodeHasPrefix applies the HasPrefix predicate on the "bps_code" field.
func BpsCodeHasPrefix(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldHasPrefix(FieldBpsCode, v))
}

// BpsCodeHasSuffix applies the HasSuffix predicate on the "bps_code" field.
func BpsCodeHasSuffix(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldHasSuffix(FieldBpsCode, v))
}

// BpsCodeEqualFold applies the EqualFold predicate on the "bps_code" field.
func BpsCodeEqualFold(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEqualFold(FieldBpsCode, v))
}

// BpsCodeContainsFold applies the ContainsFold predicate on the "bps_code" field.
func BpsCodeContainsFold(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldContainsFold(FieldBpsCode, v))
}

// PostalCodeEQ applies the EQ predicate on the "postal_code" field.
func PostalCodeEQ(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldPostalCode, v))
}

// PostalCodeNEQ applies the NEQ predicate on the "postal_code" field.
func PostalCodeNEQ(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNEQ(FieldPostalCode, v))
}

// PostalCodeIn applies the In predicate on the "postal_code" field.
func PostalCodeIn(vs ...string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldIn(FieldPostalCode, vs...))
}

// PostalCodeNotIn applies the NotIn predicate on the "postal_code" field.
func PostalCodeNotIn(vs ...string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNotIn(FieldPostalCode, vs...))
}

// PostalCodeGT applies the GT predicate on the "postal_code" field.
func PostalCodeGT(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGT(FieldPostalCode, v))
}

// PostalCodeGTE applies the GTE predicate on the "postal_code" field.
func PostalCodeGTE(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGTE(FieldPostalCode, v))
}

// PostalCodeLT applies the LT predicate on the "postal_code" field.
func PostalCodeLT(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLT(FieldPostalCode, v))
}

// PostalCodeLTE applies the LTE predicate on the "postal_code" field.
func PostalCodeLTE(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLTE(FieldPostalCode, v))
}

// PostalCodeContains applies the Contains predicate on the "postal_code" field.
func PostalCodeContains(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldContains(FieldPostalCode, v))
}

// PostalCodeHasPrefix applies the HasPrefix predicate on the "postal_code" field.
func PostalCodeHasPrefix(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldHasPrefix(FieldPostalCode, v))
}

// PostalCodeHasSuffix applies the HasSuffix predicate on the "postal_code" field.
func PostalCodeHasSuffix(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldHasSuffix(FieldPostalCode, v))
}

// PostalCodeEqualFold applies the EqualFold predicate on the "postal_code" field.
func PostalCodeEqualFold(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEqualFold(FieldPostalCode, v))
}

// PostalCodeContainsFold applies the ContainsFold predicate on the "postal_code" field.
func PostalCodeContainsFold(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldContainsFold(FieldPostalCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Subdistrict {
	return predicate.Subdistrict(sql.FieldContainsFold(FieldName, v))
}

// HasDistrict applies the HasEdge predicate on the "district" edge.
func HasDistrict() predicate.Subdistrict {
	return predicate.Subdistrict(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DistrictTable, DistrictColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDistrictWith applies the HasEdge predicate on the "district" edge with a given conditions (other predicates).
func HasDistrictWith(preds ...predicate.District) predicate.Subdistrict {
	return predicate.Subdistrict(func(s *sql.Selector) {
		step := newDistrictStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPmiLocation applies the HasEdge predicate on the "pmi_location" edge.
func HasPmiLocation() predicate.Subdistrict {
	return predicate.Subdistrict(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PmiLocationTable, PmiLocationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPmiLocationWith applies the HasEdge predicate on the "pmi_location" edge with a given conditions (other predicates).
func HasPmiLocationWith(preds ...predicate.PMILocation) predicate.Subdistrict {
	return predicate.Subdistrict(func(s *sql.Selector) {
		step := newPmiLocationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subdistrict) predicate.Subdistrict {
	return predicate.Subdistrict(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subdistrict) predicate.Subdistrict {
	return predicate.Subdistrict(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subdistrict) predicate.Subdistrict {
	return predicate.Subdistrict(sql.NotPredicates(p))
}
