// Code generated by ent, DO NOT EDIT.

package account

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldNationalIDHash holds the string denoting the national_id_hash field in the database.
	FieldNationalIDHash = "national_id_hash"
	// FieldFullName holds the string denoting the full_name field in the database.
	FieldFullName = "full_name"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCountryIsoCode holds the string denoting the country_iso_code field in the database.
	FieldCountryIsoCode = "country_iso_code"
	// FieldDialCode holds the string denoting the dial_code field in the database.
	FieldDialCode = "dial_code"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldActivated holds the string denoting the activated field in the database.
	FieldActivated = "activated"
	// FieldLocked holds the string denoting the locked field in the database.
	FieldLocked = "locked"
	// FieldTempLockedAt holds the string denoting the temp_locked_at field in the database.
	FieldTempLockedAt = "temp_locked_at"
	// EdgeBlood holds the string denoting the blood edge name in mutations.
	EdgeBlood = "blood"
	// EdgePassword holds the string denoting the password edge name in mutations.
	EdgePassword = "password"
	// Table holds the table name of the account in the database.
	Table = "accounts"
	// BloodTable is the table that holds the blood relation/edge.
	BloodTable = "bloods"
	// BloodInverseTable is the table name for the Blood entity.
	// It exists in this package in order to avoid circular dependency with the "blood" package.
	BloodInverseTable = "bloods"
	// BloodColumn is the table column denoting the blood relation/edge.
	BloodColumn = "blood_id"
	// PasswordTable is the table that holds the password relation/edge.
	PasswordTable = "passwords"
	// PasswordInverseTable is the table name for the Password entity.
	// It exists in this package in order to avoid circular dependency with the "password" package.
	PasswordInverseTable = "passwords"
	// PasswordColumn is the table column denoting the password relation/edge.
	PasswordColumn = "password_id"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldNationalIDHash,
	FieldFullName,
	FieldGender,
	FieldEmail,
	FieldCountryIsoCode,
	FieldDialCode,
	FieldPhoneNumber,
	FieldActivated,
	FieldLocked,
	FieldTempLockedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt int64
	// CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	CreatedAtValidator func(int64) error
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() int64
	// UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	UpdatedAtValidator func(int64) error
	// DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	DeletedAtValidator func(int64) error
	// NationalIDHashValidator is a validator for the "national_id_hash" field. It is called by the builders before save.
	NationalIDHashValidator func(string) error
	// FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	FullNameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// CountryIsoCodeValidator is a validator for the "country_iso_code" field. It is called by the builders before save.
	CountryIsoCodeValidator func(string) error
	// PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	PhoneNumberValidator func(string) error
	// DefaultActivated holds the default value on creation for the "activated" field.
	DefaultActivated bool
	// DefaultLocked holds the default value on creation for the "locked" field.
	DefaultLocked bool
	// TempLockedAtValidator is a validator for the "temp_locked_at" field. It is called by the builders before save.
	TempLockedAtValidator func(int64) error
)

// Gender defines the type for the "gender" enum field.
type Gender string

// Gender values.
const (
	GenderFEMALE Gender = "FEMALE"
	GenderMALE   Gender = "MALE"
)

func (ge Gender) String() string {
	return string(ge)
}

// GenderValidator is a validator for the "gender" field enum values. It is called by the builders before save.
func GenderValidator(ge Gender) error {
	switch ge {
	case GenderFEMALE, GenderMALE:
		return nil
	default:
		return fmt.Errorf("account: invalid enum value for gender field: %q", ge)
	}
}

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByNationalIDHash orders the results by the national_id_hash field.
func ByNationalIDHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNationalIDHash, opts...).ToFunc()
}

// ByFullName orders the results by the full_name field.
func ByFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullName, opts...).ToFunc()
}

// ByGender orders the results by the gender field.
func ByGender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGender, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByCountryIsoCode orders the results by the country_iso_code field.
func ByCountryIsoCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountryIsoCode, opts...).ToFunc()
}

// ByDialCode orders the results by the dial_code field.
func ByDialCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDialCode, opts...).ToFunc()
}

// ByPhoneNumber orders the results by the phone_number field.
func ByPhoneNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoneNumber, opts...).ToFunc()
}

// ByActivated orders the results by the activated field.
func ByActivated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivated, opts...).ToFunc()
}

// ByLocked orders the results by the locked field.
func ByLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocked, opts...).ToFunc()
}

// ByTempLockedAt orders the results by the temp_locked_at field.
func ByTempLockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTempLockedAt, opts...).ToFunc()
}

// ByBloodField orders the results by blood field.
func ByBloodField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBloodStep(), sql.OrderByField(field, opts...))
	}
}

// ByPasswordField orders the results by password field.
func ByPasswordField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPasswordStep(), sql.OrderByField(field, opts...))
	}
}
func newBloodStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BloodInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, BloodTable, BloodColumn),
	)
}
func newPasswordStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PasswordInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PasswordTable, PasswordColumn),
	)
}
