// Code generated by ent, DO NOT EDIT.

package pmilocation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pmilocation type in the database.
	Label = "pmi_location"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBedCapacities holds the string denoting the bed_capacities field in the database.
	FieldBedCapacities = "bed_capacities"
	// FieldLatLng holds the string denoting the lat_lng field in the database.
	FieldLatLng = "lat_lng"
	// FieldStreet holds the string denoting the street field in the database.
	FieldStreet = "street"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDialCode holds the string denoting the dial_code field in the database.
	FieldDialCode = "dial_code"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldOpensAt holds the string denoting the opens_at field in the database.
	FieldOpensAt = "opens_at"
	// FieldClosesAt holds the string denoting the closes_at field in the database.
	FieldClosesAt = "closes_at"
	// EdgeSubdistrict holds the string denoting the subdistrict edge name in mutations.
	EdgeSubdistrict = "subdistrict"
	// Table holds the table name of the pmilocation in the database.
	Table = "pmi_locations"
	// SubdistrictTable is the table that holds the subdistrict relation/edge.
	SubdistrictTable = "pmi_locations"
	// SubdistrictInverseTable is the table name for the Subdistrict entity.
	// It exists in this package in order to avoid circular dependency with the "subdistrict" package.
	SubdistrictInverseTable = "subdistricts"
	// SubdistrictColumn is the table column denoting the subdistrict relation/edge.
	SubdistrictColumn = "subdistrict_id"
)

// Columns holds all SQL columns for pmilocation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldBedCapacities,
	FieldLatLng,
	FieldStreet,
	FieldEmail,
	FieldDialCode,
	FieldPhoneNumber,
	FieldOpensAt,
	FieldClosesAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pmi_locations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"subdistrict_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	CreatedAtValidator func(int64) error
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() int64
	// UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	UpdatedAtValidator func(int64) error
	// DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	DeletedAtValidator func(int64) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultBedCapacities holds the default value on creation for the "bed_capacities" field.
	DefaultBedCapacities int16
	// BedCapacitiesValidator is a validator for the "bed_capacities" field. It is called by the builders before save.
	BedCapacitiesValidator func(int16) error
	// StreetValidator is a validator for the "street" field. It is called by the builders before save.
	StreetValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	PhoneNumberValidator func(string) error
)

// OrderOption defines the ordering options for the PMILocation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBedCapacities orders the results by the bed_capacities field.
func ByBedCapacities(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBedCapacities, opts...).ToFunc()
}

// ByLatLng orders the results by the lat_lng field.
func ByLatLng(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatLng, opts...).ToFunc()
}

// ByStreet orders the results by the street field.
func ByStreet(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreet, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByDialCode orders the results by the dial_code field.
func ByDialCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDialCode, opts...).ToFunc()
}

// ByPhoneNumber orders the results by the phone_number field.
func ByPhoneNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhoneNumber, opts...).ToFunc()
}

// ByOpensAt orders the results by the opens_at field.
func ByOpensAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpensAt, opts...).ToFunc()
}

// ByClosesAt orders the results by the closes_at field.
func ByClosesAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosesAt, opts...).ToFunc()
}

// BySubdistrictField orders the results by subdistrict field.
func BySubdistrictField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubdistrictStep(), sql.OrderByField(field, opts...))
	}
}
func newSubdistrictStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubdistrictInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubdistrictTable, SubdistrictColumn),
	)
}
