// Code generated by ent, DO NOT EDIT.

package district

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the district type in the database.
	Label = "district"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldBpsCode holds the string denoting the bps_code field in the database.
	FieldBpsCode = "bps_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeCity holds the string denoting the city edge name in mutations.
	EdgeCity = "city"
	// EdgeSubdistrict holds the string denoting the subdistrict edge name in mutations.
	EdgeSubdistrict = "subdistrict"
	// Table holds the table name of the district in the database.
	Table = "districts"
	// CityTable is the table that holds the city relation/edge.
	CityTable = "cities"
	// CityInverseTable is the table name for the City entity.
	// It exists in this package in order to avoid circular dependency with the "city" package.
	CityInverseTable = "cities"
	// CityColumn is the table column denoting the city relation/edge.
	CityColumn = "city_id"
	// SubdistrictTable is the table that holds the subdistrict relation/edge.
	SubdistrictTable = "districts"
	// SubdistrictInverseTable is the table name for the Subdistrict entity.
	// It exists in this package in order to avoid circular dependency with the "subdistrict" package.
	SubdistrictInverseTable = "subdistricts"
	// SubdistrictColumn is the table column denoting the subdistrict relation/edge.
	SubdistrictColumn = "district_id"
)

// Columns holds all SQL columns for district fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldBpsCode,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "districts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"district_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt int64
	// CreatedAtValidator is a validator for the "created_at" field. It is called by the builders before save.
	CreatedAtValidator func(int64) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt int64
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() int64
	// UpdatedAtValidator is a validator for the "updated_at" field. It is called by the builders before save.
	UpdatedAtValidator func(int64) error
	// DeletedAtValidator is a validator for the "deleted_at" field. It is called by the builders before save.
	DeletedAtValidator func(int64) error
	// BpsCodeValidator is a validator for the "bps_code" field. It is called by the builders before save.
	BpsCodeValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the District queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByBpsCode orders the results by the bps_code field.
func ByBpsCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBpsCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCityCount orders the results by city count.
func ByCityCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCityStep(), opts...)
	}
}

// ByCity orders the results by city terms.
func ByCity(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCityStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubdistrictField orders the results by subdistrict field.
func BySubdistrictField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubdistrictStep(), sql.OrderByField(field, opts...))
	}
}
func newCityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CityTable, CityColumn),
	)
}
func newSubdistrictStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubdistrictInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubdistrictTable, SubdistrictColumn),
	)
}
