// Code generated by ent, DO NOT EDIT.

package district

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.District {
	return predicate.District(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.District {
	return predicate.District(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.District {
	return predicate.District(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.District {
	return predicate.District(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.District {
	return predicate.District(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.District {
	return predicate.District(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.District {
	return predicate.District(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.District {
	return predicate.District(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.District {
	return predicate.District(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.District {
	return predicate.District(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.District {
	return predicate.District(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int64) predicate.District {
	return predicate.District(sql.FieldEQ(FieldDeletedAt, v))
}

// BpsCode applies equality check predicate on the "bps_code" field. It's identical to BpsCodeEQ.
func BpsCode(v string) predicate.District {
	return predicate.District(sql.FieldEQ(FieldBpsCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.District {
	return predicate.District(sql.FieldEQ(FieldName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.District {
	return predicate.District(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.District {
	return predicate.District(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.District {
	return predicate.District(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.District {
	return predicate.District(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.District {
	return predicate.District(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.District {
	return predicate.District(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.District {
	return predicate.District(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.District {
	return predicate.District(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.District {
	return predicate.District(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.District {
	return predicate.District(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.District {
	return predicate.District(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.District {
	return predicate.District(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.District {
	return predicate.District(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.District {
	return predicate.District(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.District {
	return predicate.District(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.District {
	return predicate.District(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int64) predicate.District {
	return predicate.District(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int64) predicate.District {
	return predicate.District(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int64) predicate.District {
	return predicate.District(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int64) predicate.District {
	return predicate.District(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int64) predicate.District {
	return predicate.District(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int64) predicate.District {
	return predicate.District(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int64) predicate.District {
	return predicate.District(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int64) predicate.District {
	return predicate.District(sql.FieldLTE(FieldDeletedAt, v))
}

// BpsCodeEQ applies the EQ predicate on the "bps_code" field.
func BpsCodeEQ(v string) predicate.District {
	return predicate.District(sql.FieldEQ(FieldBpsCode, v))
}

// BpsCodeNEQ applies the NEQ predicate on the "bps_code" field.
func BpsCodeNEQ(v string) predicate.District {
	return predicate.District(sql.FieldNEQ(FieldBpsCode, v))
}

// BpsCodeIn applies the In predicate on the "bps_code" field.
func BpsCodeIn(vs ...string) predicate.District {
	return predicate.District(sql.FieldIn(FieldBpsCode, vs...))
}

// BpsCodeNotIn applies the NotIn predicate on the "bps_code" field.
func BpsCodeNotIn(vs ...string) predicate.District {
	return predicate.District(sql.FieldNotIn(FieldBpsCode, vs...))
}

// BpsCodeGT applies the GT predicate on the "bps_code" field.
func BpsCodeGT(v string) predicate.District {
	return predicate.District(sql.FieldGT(FieldBpsCode, v))
}

// BpsCodeGTE applies the GTE predicate on the "bps_code" field.
func BpsCodeGTE(v string) predicate.District {
	return predicate.District(sql.FieldGTE(FieldBpsCode, v))
}

// BpsCodeLT applies the LT predicate on the "bps_code" field.
func BpsCodeLT(v string) predicate.District {
	return predicate.District(sql.FieldLT(FieldBpsCode, v))
}

// BpsCodeLTE applies the LTE predicate on the "bps_code" field.
func BpsCodeLTE(v string) predicate.District {
	return predicate.District(sql.FieldLTE(FieldBpsCode, v))
}

// BpsCodeContains applies the Contains predicate on the "bps_code" field.
func BpsCodeContains(v string) predicate.District {
	return predicate.District(sql.FieldContains(FieldBpsCode, v))
}

// BpsCodeHasPrefix applies the HasPrefix predicate on the "bps_code" field.
func BpsCodeHasPrefix(v string) predicate.District {
	return predicate.District(sql.FieldHasPrefix(FieldBpsCode, v))
}

// BpsCodeHasSuffix applies the HasSuffix predicate on the "bps_code" field.
func BpsCodeHasSuffix(v string) predicate.District {
	return predicate.District(sql.FieldHasSuffix(FieldBpsCode, v))
}

// BpsCodeEqualFold applies the EqualFold predicate on the "bps_code" field.
func BpsCodeEqualFold(v string) predicate.District {
	return predicate.District(sql.FieldEqualFold(FieldBpsCode, v))
}

// BpsCodeContainsFold applies the ContainsFold predicate on the "bps_code" field.
func BpsCodeContainsFold(v string) predicate.District {
	return predicate.District(sql.FieldContainsFold(FieldBpsCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.District {
	return predicate.District(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.District {
	return predicate.District(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.District {
	return predicate.District(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.District {
	return predicate.District(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.District {
	return predicate.District(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.District {
	return predicate.District(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.District {
	return predicate.District(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.District {
	return predicate.District(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.District {
	return predicate.District(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.District {
	return predicate.District(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.District {
	return predicate.District(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.District {
	return predicate.District(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.District {
	return predicate.District(sql.FieldContainsFold(FieldName, v))
}

// HasCity applies the HasEdge predicate on the "city" edge.
func HasCity() predicate.District {
	return predicate.District(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CityTable, CityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCityWith applies the HasEdge predicate on the "city" edge with a given conditions (other predicates).
func HasCityWith(preds ...predicate.City) predicate.District {
	return predicate.District(func(s *sql.Selector) {
		step := newCityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubdistrict applies the HasEdge predicate on the "subdistrict" edge.
func HasSubdistrict() predicate.District {
	return predicate.District(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubdistrictTable, SubdistrictColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubdistrictWith applies the HasEdge predicate on the "subdistrict" edge with a given conditions (other predicates).
func HasSubdistrictWith(preds ...predicate.Subdistrict) predicate.District {
	return predicate.District(func(s *sql.Selector) {
		step := newSubdistrictStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.District) predicate.District {
	return predicate.District(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.District) predicate.District {
	return predicate.District(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.District) predicate.District {
	return predicate.District(sql.NotPredicates(p))
}
