// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/ent/account"
	"github.com/megalodev/setetes/ent/blood"
	"github.com/megalodev/setetes/ent/password"
)

// Account is the model entity for the Account schema.
type Account struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *int64 `json:"updated_at"`
	// Represents soft delete timestamp in milliseconds.
	DeletedAt *int64 `json:"deleted_at"`
	// SHA256 hash of a user's national identity number (e.g., KTP). Stored securely to avoid saving raw identity numbers.
	NationalIDHash string `json:"-"`
	// FullName holds the value of the "full_name" field.
	FullName string `json:"full_name"`
	// Gender holds the value of the "gender" field.
	Gender account.Gender `json:"gender"`
	// Email holds the value of the "email" field.
	Email string `json:"email"`
	// ISO 3166-1 alpha-2 country code representing the user's country (e.g., ID for Indonesia, US for United States).
	CountryIsoCode string `json:"country_iso_code"`
	// International dialing code of the user's country (e.g., +62 for Indonesia, +1 for United States). Used for constructing complete phone numbers.
	DialCode string `json:"dial_code"`
	// PhoneNumber holds the value of the "phone_number" field.
	PhoneNumber string `json:"phone_number"`
	// Activated holds the value of the "activated" field.
	Activated bool `json:"activated"`
	// Permanently locked by this account.
	Locked bool `json:"locked"`
	// Temporary locked by this account based on time milliseconds.
	TempLockedAt *int64 `json:"temp_locked_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountQuery when eager-loading is set.
	Edges        AccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountEdges holds the relations/edges for other nodes in the graph.
type AccountEdges struct {
	// Blood holds the value of the blood edge.
	Blood *Blood `json:"blood,omitempty"`
	// Password holds the value of the password edge.
	Password *Password `json:"password,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BloodOrErr returns the Blood value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEdges) BloodOrErr() (*Blood, error) {
	if e.Blood != nil {
		return e.Blood, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: blood.Label}
	}
	return nil, &NotLoadedError{edge: "blood"}
}

// PasswordOrErr returns the Password value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEdges) PasswordOrErr() (*Password, error) {
	if e.Password != nil {
		return e.Password, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: password.Label}
	}
	return nil, &NotLoadedError{edge: "password"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Account) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case account.FieldActivated, account.FieldLocked:
			values[i] = new(sql.NullBool)
		case account.FieldCreatedAt, account.FieldUpdatedAt, account.FieldDeletedAt, account.FieldTempLockedAt:
			values[i] = new(sql.NullInt64)
		case account.FieldNationalIDHash, account.FieldFullName, account.FieldGender, account.FieldEmail, account.FieldCountryIsoCode, account.FieldDialCode, account.FieldPhoneNumber:
			values[i] = new(sql.NullString)
		case account.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Account fields.
func (_m *Account) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case account.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case account.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case account.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(int64)
				*_m.UpdatedAt = value.Int64
			}
		case account.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(int64)
				*_m.DeletedAt = value.Int64
			}
		case account.FieldNationalIDHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field national_id_hash", values[i])
			} else if value.Valid {
				_m.NationalIDHash = value.String
			}
		case account.FieldFullName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_name", values[i])
			} else if value.Valid {
				_m.FullName = value.String
			}
		case account.FieldGender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				_m.Gender = account.Gender(value.String)
			}
		case account.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case account.FieldCountryIsoCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country_iso_code", values[i])
			} else if value.Valid {
				_m.CountryIsoCode = value.String
			}
		case account.FieldDialCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dial_code", values[i])
			} else if value.Valid {
				_m.DialCode = value.String
			}
		case account.FieldPhoneNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone_number", values[i])
			} else if value.Valid {
				_m.PhoneNumber = value.String
			}
		case account.FieldActivated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field activated", values[i])
			} else if value.Valid {
				_m.Activated = value.Bool
			}
		case account.FieldLocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field locked", values[i])
			} else if value.Valid {
				_m.Locked = value.Bool
			}
		case account.FieldTempLockedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field temp_locked_at", values[i])
			} else if value.Valid {
				_m.TempLockedAt = new(int64)
				*_m.TempLockedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Account.
// This includes values selected through modifiers, order, etc.
func (_m *Account) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBlood queries the "blood" edge of the Account entity.
func (_m *Account) QueryBlood() *BloodQuery {
	return NewAccountClient(_m.config).QueryBlood(_m)
}

// QueryPassword queries the "password" edge of the Account entity.
func (_m *Account) QueryPassword() *PasswordQuery {
	return NewAccountClient(_m.config).QueryPassword(_m)
}

// Update returns a builder for updating this Account.
// Note that you need to call Account.Unwrap() before calling this method if this Account
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Account) Update() *AccountUpdateOne {
	return NewAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Account entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Account) Unwrap() *Account {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Account is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Account) String() string {
	var builder strings.Builder
	builder.WriteString("Account(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("national_id_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("full_name=")
	builder.WriteString(_m.FullName)
	builder.WriteString(", ")
	builder.WriteString("gender=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gender))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("country_iso_code=")
	builder.WriteString(_m.CountryIsoCode)
	builder.WriteString(", ")
	builder.WriteString("dial_code=")
	builder.WriteString(_m.DialCode)
	builder.WriteString(", ")
	builder.WriteString("phone_number=")
	builder.WriteString(_m.PhoneNumber)
	builder.WriteString(", ")
	builder.WriteString("activated=")
	builder.WriteString(fmt.Sprintf("%v", _m.Activated))
	builder.WriteString(", ")
	builder.WriteString("locked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Locked))
	builder.WriteString(", ")
	if v := _m.TempLockedAt; v != nil {
		builder.WriteString("temp_locked_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Accounts is a parsable slice of Account.
type Accounts []*Account
