// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/ent/account"
	"github.com/megalodev/setetes/ent/blood"
	"github.com/megalodev/setetes/ent/predicate"
)

// BloodUpdate is the builder for updating Blood entities.
type BloodUpdate struct {
	config
	hooks    []Hook
	mutation *BloodMutation
}

// Where appends a list predicates to the BloodUpdate builder.
func (_u *BloodUpdate) Where(ps ...predicate.Blood) *BloodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BloodUpdate) SetUpdatedAt(v int64) *BloodUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *BloodUpdate) AddUpdatedAt(v int64) *BloodUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BloodUpdate) SetDeletedAt(v int64) *BloodUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BloodUpdate) SetNillableDeletedAt(v *int64) *BloodUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *BloodUpdate) AddDeletedAt(v int64) *BloodUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetGroup sets the "group" field.
func (_u *BloodUpdate) SetGroup(v blood.Group) *BloodUpdate {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *BloodUpdate) SetNillableGroup(v *blood.Group) *BloodUpdate {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetRhesus sets the "rhesus" field.
func (_u *BloodUpdate) SetRhesus(v blood.Rhesus) *BloodUpdate {
	_u.mutation.SetRhesus(v)
	return _u
}

// SetNillableRhesus sets the "rhesus" field if the given value is not nil.
func (_u *BloodUpdate) SetNillableRhesus(v *blood.Rhesus) *BloodUpdate {
	if v != nil {
		_u.SetRhesus(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *BloodUpdate) SetAccountID(id uuid.UUID) *BloodUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *BloodUpdate) SetAccount(v *Account) *BloodUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the BloodMutation object of the builder.
func (_u *BloodUpdate) Mutation() *BloodMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *BloodUpdate) ClearAccount() *BloodUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BloodUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BloodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BloodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BloodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BloodUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blood.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BloodUpdate) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := blood.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "Blood.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := blood.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "Blood.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Group(); ok {
		if err := blood.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "Blood.group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rhesus(); ok {
		if err := blood.RhesusValidator(v); err != nil {
			return &ValidationError{Name: "rhesus", err: fmt.Errorf(`ent: validator failed for field "Blood.rhesus": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Blood.account"`)
	}
	return nil
}

func (_u *BloodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blood.Table, blood.Columns, sqlgraph.NewFieldSpec(blood.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blood.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(blood.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(blood.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(blood.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(blood.FieldGroup, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Rhesus(); ok {
		_spec.SetField(blood.FieldRhesus, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blood.AccountTable,
			Columns: []string{blood.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blood.AccountTable,
			Columns: []string{blood.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blood.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BloodUpdateOne is the builder for updating a single Blood entity.
type BloodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BloodMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BloodUpdateOne) SetUpdatedAt(v int64) *BloodUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *BloodUpdateOne) AddUpdatedAt(v int64) *BloodUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BloodUpdateOne) SetDeletedAt(v int64) *BloodUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BloodUpdateOne) SetNillableDeletedAt(v *int64) *BloodUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *BloodUpdateOne) AddDeletedAt(v int64) *BloodUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetGroup sets the "group" field.
func (_u *BloodUpdateOne) SetGroup(v blood.Group) *BloodUpdateOne {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *BloodUpdateOne) SetNillableGroup(v *blood.Group) *BloodUpdateOne {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetRhesus sets the "rhesus" field.
func (_u *BloodUpdateOne) SetRhesus(v blood.Rhesus) *BloodUpdateOne {
	_u.mutation.SetRhesus(v)
	return _u
}

// SetNillableRhesus sets the "rhesus" field if the given value is not nil.
func (_u *BloodUpdateOne) SetNillableRhesus(v *blood.Rhesus) *BloodUpdateOne {
	if v != nil {
		_u.SetRhesus(*v)
	}
	return _u
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *BloodUpdateOne) SetAccountID(id uuid.UUID) *BloodUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *BloodUpdateOne) SetAccount(v *Account) *BloodUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the BloodMutation object of the builder.
func (_u *BloodUpdateOne) Mutation() *BloodMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *BloodUpdateOne) ClearAccount() *BloodUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the BloodUpdate builder.
func (_u *BloodUpdateOne) Where(ps ...predicate.Blood) *BloodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BloodUpdateOne) Select(field string, fields ...string) *BloodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Blood entity.
func (_u *BloodUpdateOne) Save(ctx context.Context) (*Blood, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BloodUpdateOne) SaveX(ctx context.Context) *Blood {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BloodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BloodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BloodUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := blood.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BloodUpdateOne) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := blood.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "Blood.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := blood.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "Blood.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Group(); ok {
		if err := blood.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "Blood.group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rhesus(); ok {
		if err := blood.RhesusValidator(v); err != nil {
			return &ValidationError{Name: "rhesus", err: fmt.Errorf(`ent: validator failed for field "Blood.rhesus": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Blood.account"`)
	}
	return nil
}

func (_u *BloodUpdateOne) sqlSave(ctx context.Context) (_node *Blood, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(blood.Table, blood.Columns, sqlgraph.NewFieldSpec(blood.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Blood.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blood.FieldID)
		for _, f := range fields {
			if !blood.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blood.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blood.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(blood.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(blood.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(blood.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(blood.FieldGroup, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Rhesus(); ok {
		_spec.SetField(blood.FieldRhesus, field.TypeEnum, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blood.AccountTable,
			Columns: []string{blood.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blood.AccountTable,
			Columns: []string{blood.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Blood{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blood.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
