// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/ent/account"
	"github.com/megalodev/setetes/ent/blood"
)

// BloodCreate is the builder for creating a Blood entity.
type BloodCreate struct {
	config
	mutation *BloodMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *BloodCreate) SetCreatedAt(v int64) *BloodCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BloodCreate) SetNillableCreatedAt(v *int64) *BloodCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BloodCreate) SetUpdatedAt(v int64) *BloodCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BloodCreate) SetNillableUpdatedAt(v *int64) *BloodCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BloodCreate) SetDeletedAt(v int64) *BloodCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetGroup sets the "group" field.
func (_c *BloodCreate) SetGroup(v blood.Group) *BloodCreate {
	_c.mutation.SetGroup(v)
	return _c
}

// SetRhesus sets the "rhesus" field.
func (_c *BloodCreate) SetRhesus(v blood.Rhesus) *BloodCreate {
	_c.mutation.SetRhesus(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BloodCreate) SetID(v uuid.UUID) *BloodCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BloodCreate) SetNillableID(v *uuid.UUID) *BloodCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_c *BloodCreate) SetAccountID(id uuid.UUID) *BloodCreate {
	_c.mutation.SetAccountID(id)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *BloodCreate) SetAccount(v *Account) *BloodCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the BloodMutation object of the builder.
func (_c *BloodCreate) Mutation() *BloodMutation {
	return _c.mutation
}

// Save creates the Blood in the database.
func (_c *BloodCreate) Save(ctx context.Context) (*Blood, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BloodCreate) SaveX(ctx context.Context) *Blood {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BloodCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BloodCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BloodCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := blood.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := blood.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := blood.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BloodCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Blood.created_at"`)}
	}
	if v, ok := _c.mutation.CreatedAt(); ok {
		if err := blood.CreatedAtValidator(v); err != nil {
			return &ValidationError{Name: "created_at", err: fmt.Errorf(`ent: validator failed for field "Blood.created_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Blood.updated_at"`)}
	}
	if v, ok := _c.mutation.UpdatedAt(); ok {
		if err := blood.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "Blood.updated_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Blood.deleted_at"`)}
	}
	if v, ok := _c.mutation.DeletedAt(); ok {
		if err := blood.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "Blood.deleted_at": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Group(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required field "Blood.group"`)}
	}
	if v, ok := _c.mutation.Group(); ok {
		if err := blood.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "Blood.group": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rhesus(); !ok {
		return &ValidationError{Name: "rhesus", err: errors.New(`ent: missing required field "Blood.rhesus"`)}
	}
	if v, ok := _c.mutation.Rhesus(); ok {
		if err := blood.RhesusValidator(v); err != nil {
			return &ValidationError{Name: "rhesus", err: fmt.Errorf(`ent: validator failed for field "Blood.rhesus": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "Blood.account"`)}
	}
	return nil
}

func (_c *BloodCreate) sqlSave(ctx context.Context) (*Blood, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BloodCreate) createSpec() (*Blood, *sqlgraph.CreateSpec) {
	var (
		_node = &Blood{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blood.Table, sqlgraph.NewFieldSpec(blood.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blood.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(blood.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(blood.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Group(); ok {
		_spec.SetField(blood.FieldGroup, field.TypeEnum, value)
		_node.Group = value
	}
	if value, ok := _c.mutation.Rhesus(); ok {
		_spec.SetField(blood.FieldRhesus, field.TypeEnum, value)
		_node.Rhesus = &value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   blood.AccountTable,
			Columns: []string{blood.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.blood_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BloodCreateBulk is the builder for creating many Blood entities in bulk.
type BloodCreateBulk struct {
	config
	err      error
	builders []*BloodCreate
}

// Save creates the Blood entities in the database.
func (_c *BloodCreateBulk) Save(ctx context.Context) ([]*Blood, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Blood, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BloodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BloodCreateBulk) SaveX(ctx context.Context) []*Blood {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BloodCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BloodCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
