// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/ent/city"
	"github.com/megalodev/setetes/ent/district"
	"github.com/megalodev/setetes/ent/predicate"
	"github.com/megalodev/setetes/ent/province"
)

// CityUpdate is the builder for updating City entities.
type CityUpdate struct {
	config
	hooks    []Hook
	mutation *CityMutation
}

// Where appends a list predicates to the CityUpdate builder.
func (_u *CityUpdate) Where(ps ...predicate.City) *CityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CityUpdate) SetUpdatedAt(v int64) *CityUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *CityUpdate) AddUpdatedAt(v int64) *CityUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CityUpdate) SetDeletedAt(v int64) *CityUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CityUpdate) SetNillableDeletedAt(v *int64) *CityUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *CityUpdate) AddDeletedAt(v int64) *CityUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetBpsCode sets the "bps_code" field.
func (_u *CityUpdate) SetBpsCode(v string) *CityUpdate {
	_u.mutation.SetBpsCode(v)
	return _u
}

// SetNillableBpsCode sets the "bps_code" field if the given value is not nil.
func (_u *CityUpdate) SetNillableBpsCode(v *string) *CityUpdate {
	if v != nil {
		_u.SetBpsCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CityUpdate) SetName(v string) *CityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CityUpdate) SetNillableName(v *string) *CityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddProvinceIDs adds the "province" edge to the Province entity by IDs.
func (_u *CityUpdate) AddProvinceIDs(ids ...uuid.UUID) *CityUpdate {
	_u.mutation.AddProvinceIDs(ids...)
	return _u
}

// AddProvince adds the "province" edges to the Province entity.
func (_u *CityUpdate) AddProvince(v ...*Province) *CityUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProvinceIDs(ids...)
}

// SetDistrictID sets the "district" edge to the District entity by ID.
func (_u *CityUpdate) SetDistrictID(id uuid.UUID) *CityUpdate {
	_u.mutation.SetDistrictID(id)
	return _u
}

// SetDistrict sets the "district" edge to the District entity.
func (_u *CityUpdate) SetDistrict(v *District) *CityUpdate {
	return _u.SetDistrictID(v.ID)
}

// Mutation returns the CityMutation object of the builder.
func (_u *CityUpdate) Mutation() *CityMutation {
	return _u.mutation
}

// ClearProvince clears all "province" edges to the Province entity.
func (_u *CityUpdate) ClearProvince() *CityUpdate {
	_u.mutation.ClearProvince()
	return _u
}

// RemoveProvinceIDs removes the "province" edge to Province entities by IDs.
func (_u *CityUpdate) RemoveProvinceIDs(ids ...uuid.UUID) *CityUpdate {
	_u.mutation.RemoveProvinceIDs(ids...)
	return _u
}

// RemoveProvince removes "province" edges to Province entities.
func (_u *CityUpdate) RemoveProvince(v ...*Province) *CityUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProvinceIDs(ids...)
}

// ClearDistrict clears the "district" edge to the District entity.
func (_u *CityUpdate) ClearDistrict() *CityUpdate {
	_u.mutation.ClearDistrict()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := city.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CityUpdate) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := city.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "City.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := city.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "City.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BpsCode(); ok {
		if err := city.BpsCodeValidator(v); err != nil {
			return &ValidationError{Name: "bps_code", err: fmt.Errorf(`ent: validator failed for field "City.bps_code": %w`, err)}
		}
	}
	if _u.mutation.DistrictCleared() && len(_u.mutation.DistrictIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "City.district"`)
	}
	return nil
}

func (_u *CityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(city.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(city.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(city.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(city.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BpsCode(); ok {
		_spec.SetField(city.FieldBpsCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(city.FieldName, field.TypeString, value)
	}
	if _u.mutation.ProvinceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ProvinceTable,
			Columns: []string{city.ProvinceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(province.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProvinceIDs(); len(nodes) > 0 && !_u.mutation.ProvinceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ProvinceTable,
			Columns: []string{city.ProvinceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(province.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProvinceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ProvinceTable,
			Columns: []string{city.ProvinceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(province.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.DistrictTable,
			Columns: []string{city.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.DistrictTable,
			Columns: []string{city.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CityUpdateOne is the builder for updating a single City entity.
type CityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CityUpdateOne) SetUpdatedAt(v int64) *CityUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *CityUpdateOne) AddUpdatedAt(v int64) *CityUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CityUpdateOne) SetDeletedAt(v int64) *CityUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableDeletedAt(v *int64) *CityUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *CityUpdateOne) AddDeletedAt(v int64) *CityUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetBpsCode sets the "bps_code" field.
func (_u *CityUpdateOne) SetBpsCode(v string) *CityUpdateOne {
	_u.mutation.SetBpsCode(v)
	return _u
}

// SetNillableBpsCode sets the "bps_code" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableBpsCode(v *string) *CityUpdateOne {
	if v != nil {
		_u.SetBpsCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CityUpdateOne) SetName(v string) *CityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableName(v *string) *CityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddProvinceIDs adds the "province" edge to the Province entity by IDs.
func (_u *CityUpdateOne) AddProvinceIDs(ids ...uuid.UUID) *CityUpdateOne {
	_u.mutation.AddProvinceIDs(ids...)
	return _u
}

// AddProvince adds the "province" edges to the Province entity.
func (_u *CityUpdateOne) AddProvince(v ...*Province) *CityUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProvinceIDs(ids...)
}

// SetDistrictID sets the "district" edge to the District entity by ID.
func (_u *CityUpdateOne) SetDistrictID(id uuid.UUID) *CityUpdateOne {
	_u.mutation.SetDistrictID(id)
	return _u
}

// SetDistrict sets the "district" edge to the District entity.
func (_u *CityUpdateOne) SetDistrict(v *District) *CityUpdateOne {
	return _u.SetDistrictID(v.ID)
}

// Mutation returns the CityMutation object of the builder.
func (_u *CityUpdateOne) Mutation() *CityMutation {
	return _u.mutation
}

// ClearProvince clears all "province" edges to the Province entity.
func (_u *CityUpdateOne) ClearProvince() *CityUpdateOne {
	_u.mutation.ClearProvince()
	return _u
}

// RemoveProvinceIDs removes the "province" edge to Province entities by IDs.
func (_u *CityUpdateOne) RemoveProvinceIDs(ids ...uuid.UUID) *CityUpdateOne {
	_u.mutation.RemoveProvinceIDs(ids...)
	return _u
}

// RemoveProvince removes "province" edges to Province entities.
func (_u *CityUpdateOne) RemoveProvince(v ...*Province) *CityUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProvinceIDs(ids...)
}

// ClearDistrict clears the "district" edge to the District entity.
func (_u *CityUpdateOne) ClearDistrict() *CityUpdateOne {
	_u.mutation.ClearDistrict()
	return _u
}

// Where appends a list predicates to the CityUpdate builder.
func (_u *CityUpdateOne) Where(ps ...predicate.City) *CityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CityUpdateOne) Select(field string, fields ...string) *CityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated City entity.
func (_u *CityUpdateOne) Save(ctx context.Context) (*City, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CityUpdateOne) SaveX(ctx context.Context) *City {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := city.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CityUpdateOne) check() error {
	if v, ok := _u.mutation.UpdatedAt(); ok {
		if err := city.UpdatedAtValidator(v); err != nil {
			return &ValidationError{Name: "updated_at", err: fmt.Errorf(`ent: validator failed for field "City.updated_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedAt(); ok {
		if err := city.DeletedAtValidator(v); err != nil {
			return &ValidationError{Name: "deleted_at", err: fmt.Errorf(`ent: validator failed for field "City.deleted_at": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BpsCode(); ok {
		if err := city.BpsCodeValidator(v); err != nil {
			return &ValidationError{Name: "bps_code", err: fmt.Errorf(`ent: validator failed for field "City.bps_code": %w`, err)}
		}
	}
	if _u.mutation.DistrictCleared() && len(_u.mutation.DistrictIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "City.district"`)
	}
	return nil
}

func (_u *CityUpdateOne) sqlSave(ctx context.Context) (_node *City, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "City.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, city.FieldID)
		for _, f := range fields {
			if !city.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != city.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(city.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(city.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(city.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(city.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BpsCode(); ok {
		_spec.SetField(city.FieldBpsCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(city.FieldName, field.TypeString, value)
	}
	if _u.mutation.ProvinceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ProvinceTable,
			Columns: []string{city.ProvinceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(province.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProvinceIDs(); len(nodes) > 0 && !_u.mutation.ProvinceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ProvinceTable,
			Columns: []string{city.ProvinceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(province.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProvinceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ProvinceTable,
			Columns: []string{city.ProvinceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(province.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DistrictCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.DistrictTable,
			Columns: []string{city.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DistrictIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.DistrictTable,
			Columns: []string{city.DistrictColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(district.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &City{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
