// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/megalodev/setetes/ent/pmilocation"
	"github.com/megalodev/setetes/ent/subdistrict"
)

// Subdistrict is the model entity for the Subdistrict schema.
type Subdistrict struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *int64 `json:"updated_at"`
	// Represents soft delete timestamp in milliseconds.
	DeletedAt *int64 `json:"deleted_at"`
	// BpsCode holds the value of the "bps_code" field.
	BpsCode string `json:"bps_code"`
	// PostalCode holds the value of the "postal_code" field.
	PostalCode string `json:"postal_code"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubdistrictQuery when eager-loading is set.
	Edges          SubdistrictEdges `json:"edges"`
	subdistrict_id *uuid.UUID
	selectValues   sql.SelectValues
}

// SubdistrictEdges holds the relations/edges for other nodes in the graph.
type SubdistrictEdges struct {
	// District holds the value of the district edge.
	District []*District `json:"district,omitempty"`
	// PmiLocation holds the value of the pmi_location edge.
	PmiLocation *PMILocation `json:"pmi_location,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DistrictOrErr returns the District value or an error if the edge
// was not loaded in eager-loading.
func (e SubdistrictEdges) DistrictOrErr() ([]*District, error) {
	if e.loadedTypes[0] {
		return e.District, nil
	}
	return nil, &NotLoadedError{edge: "district"}
}

// PmiLocationOrErr returns the PmiLocation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubdistrictEdges) PmiLocationOrErr() (*PMILocation, error) {
	if e.PmiLocation != nil {
		return e.PmiLocation, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: pmilocation.Label}
	}
	return nil, &NotLoadedError{edge: "pmi_location"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subdistrict) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subdistrict.FieldCreatedAt, subdistrict.FieldUpdatedAt, subdistrict.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case subdistrict.FieldBpsCode, subdistrict.FieldPostalCode, subdistrict.FieldName:
			values[i] = new(sql.NullString)
		case subdistrict.FieldID:
			values[i] = new(uuid.UUID)
		case subdistrict.ForeignKeys[0]: // subdistrict_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subdistrict fields.
func (_m *Subdistrict) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subdistrict.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case subdistrict.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case subdistrict.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(int64)
				*_m.UpdatedAt = value.Int64
			}
		case subdistrict.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(int64)
				*_m.DeletedAt = value.Int64
			}
		case subdistrict.FieldBpsCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bps_code", values[i])
			} else if value.Valid {
				_m.BpsCode = value.String
			}
		case subdistrict.FieldPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postal_code", values[i])
			} else if value.Valid {
				_m.PostalCode = value.String
			}
		case subdistrict.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case subdistrict.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field subdistrict_id", values[i])
			} else if value.Valid {
				_m.subdistrict_id = new(uuid.UUID)
				*_m.subdistrict_id = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Subdistrict.
// This includes values selected through modifiers, order, etc.
func (_m *Subdistrict) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDistrict queries the "district" edge of the Subdistrict entity.
func (_m *Subdistrict) QueryDistrict() *DistrictQuery {
	return NewSubdistrictClient(_m.config).QueryDistrict(_m)
}

// QueryPmiLocation queries the "pmi_location" edge of the Subdistrict entity.
func (_m *Subdistrict) QueryPmiLocation() *PMILocationQuery {
	return NewSubdistrictClient(_m.config).QueryPmiLocation(_m)
}

// Update returns a builder for updating this Subdistrict.
// Note that you need to call Subdistrict.Unwrap() before calling this method if this Subdistrict
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Subdistrict) Update() *SubdistrictUpdateOne {
	return NewSubdistrictClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Subdistrict entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Subdistrict) Unwrap() *Subdistrict {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subdistrict is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Subdistrict) String() string {
	var builder strings.Builder
	builder.WriteString("Subdistrict(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("bps_code=")
	builder.WriteString(_m.BpsCode)
	builder.WriteString(", ")
	builder.WriteString("postal_code=")
	builder.WriteString(_m.PostalCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Subdistricts is a parsable slice of Subdistrict.
type Subdistricts []*Subdistrict
