// Code generated by ent, DO NOT EDIT.

package province

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the province type in the database.
	Label = "province"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBpsCode holds the string denoting the bps_code field in the database.
	FieldBpsCode = "bps_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeCity holds the string denoting the city edge name in mutations.
	EdgeCity = "city"
	// Table holds the table name of the province in the database.
	Table = "provinces"
	// CityTable is the table that holds the city relation/edge.
	CityTable = "provinces"
	// CityInverseTable is the table name for the City entity.
	// It exists in this package in order to avoid circular dependency with the "city" package.
	CityInverseTable = "cities"
	// CityColumn is the table column denoting the city relation/edge.
	CityColumn = "province_id"
)

// Columns holds all SQL columns for province fields.
var Columns = []string{
	FieldID,
	FieldBpsCode,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "provinces"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"province_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// BpsCodeValidator is a validator for the "bps_code" field. It is called by the builders before save.
	BpsCodeValidator func(string) error
)

// OrderOption defines the ordering options for the Province queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBpsCode orders the results by the bps_code field.
func ByBpsCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBpsCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCityField orders the results by city field.
func ByCityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCityStep(), sql.OrderByField(field, opts...))
	}
}
func newCityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CityTable, CityColumn),
	)
}
